### ISSUE TITLE
uncaughtException handler causes TLS certificate validation skip

### ISSUE THREAD

**Issue by praseodym** [hubotio/hubot#1046]
Me and @RickWieman stumbled upon an issue where HTTPS requests to a server with an untrusted certificate would succeed. We got this down to the following testcase:

``` coffee
HttpClient = require 'scoped-http-client'

process.on 'uncaughtException', (err) -> console.log err.stack

HttpClient.create("https://test/1/").get() (err, res, body) ->
  console.log "1: " + res.statusCode

HttpClient.create("https://test/2/").get() (err, res, body) ->
  console.log "2: " + err

HttpClient.create("https://test/3/").get() (err, res, body) ->
  console.log "3: " + res.statusCode + " -- " + err

HttpClient.create("https://test/4/").get() (err, res, body) ->
  console.log "4: " + body
```

Here, HTTP requests 1 and 3 will succeed, apparently because the use of `res.statusCode` in combination with the `uncaughtException` handler will complete the request even though a TLS certificate validation error is encountered. The output of the testcase is as follows:

```
% coffee test.coffee
TypeError: Cannot read property 'statusCode' of null
  at test/test.coffee:6:26
  at ClientRequest.<anonymous> (/test/node_modules/scoped-http-client/src/index.js:99:20)
  at ClientRequest.emit (events.js:107:17)
  at TLSSocket.socketErrorListener (_http_client.js:271:9)
  at TLSSocket.emit (events.js:129:20)
  at TLSSocket.<anonymous> (_tls_wrap.js:942:18)
  at TLSSocket.emit (events.js:104:17)
  at TLSSocket._finishInit (_tls_wrap.js:460:8)

4: null
TypeError: Cannot read property 'statusCode' of null
  at /test/test.coffee:12:26
  at ClientRequest.<anonymous> (/test/node_modules/scoped-http-client/src/index.js:99:20)
  at ClientRequest.emit (events.js:107:17)
  at TLSSocket.socketErrorListener (_http_client.js:271:9)
  at TLSSocket.emit (events.js:129:20)
  at TLSSocket.<anonymous> (_tls_wrap.js:942:18)
  at TLSSocket.emit (events.js:104:17)
  at TLSSocket._finishInit (_tls_wrap.js:460:8)

2: Error: unable to verify the first certificate
1: 200
3: 200 -- null
```

For testcases 1 and 3, the `body` variable is set after `res.statusCode` is used.

**Comment by technicalpickles** [comment]
This seems like it's a bug in https://github.com/technoweenie/node-scoped-http-client not hubot. That library in turn is just using the builtin `http` and `https` libraries, so it's possible this is reproducible just with node.

Some questions/thoughts:

* what version of node and node-scoped-http-client did you test against?
* does this problem still exist if you remove the uncaughtException handler?

**Comment by praseodym** [comment]
* I am testing against scoped-http-client@0.11.0.
* Apparently, the behaviour varies widely with different node versions:
  * node v0.10.41: all requests fail, i.e. success
  * node v0.12.9: request succeed, i.e. *failure*
  * node v4.2.4: all requests fail, i.e. success
  * node v5.3.0: all requests fail, i.e. success
* Without the uncaughtException handler, all requests fail as expected.

**Comment by technicalpickles** [comment]
Can it be reproduced with the `https` module without `scoped-http-client`?

**Comment by praseodym** [comment]
Yes. With node v0.12.9, this code will print an error _and the response body_ provided that the uncaughtException handler is defined:
```coffee
https = require 'https'

process.on 'uncaughtException', (err) -> console.log err.stack

https.get 'https://test/1/', (res) ->
  res.on 'data', (d) ->
    process.stdout.write(d)
```
Other Node versions (v0.10.41, v4.2.4 and v5.3.0) are not affected.
