### ISSUE TITLE
More documentation for custom listeners

### ISSUE THREAD

**Issue by technicalpickles** [hubotio/hubot#1055]
I've started using the custom listeners (https://github.com/github/hubot/blob/master/docs/scripting.md#custom-listeners) and ran into one caveat. If you want to do any matching on text, you need to make sure there is text. Otherwise, `EnterMessage` and `LeaveMessage` would be fired as well.

Example:

``` coffeescript
  robot.listen(
    (message) ->
      return false unless message.text

      match = message.text.match /some regex here/
      if match
         # process it further, eventually return true or match data for callback
      else
        false
```

**Comment by michaelansel** [comment]
You should probably just be looking at the message type, but maybe duck typing it is okay as well? The core uses explicit types instead of duck typing (e.g. `message instanceof TextMessage` instead of `message.text?`)

**Comment by technicalpickles** [comment]
Yeah, we could do that too.

I thought you had a pull request to get rid of typing like that, but that might have been for Listeners instead.

**Comment by michaelansel** [comment]
Ah yes, you're talking about [#986](https://github.com/github/hubot/pull/986#issuecomment-113224108). I do want to get rid of `TextListener`, but I think `Message` types are still useful.

cc #949, where we were discussing duck typing message matching

Also, cc #1058 and #1036 where there is discussion around changing the adapter interface (which might involve extending or adding `Message` subclasses)

**Comment by technicalpickles** [comment]
Another thing to document around here: anything that's non-falsey (ie not null or false) return from the matcher function is available from `response.match`. That means you can return an object, and middleware can access that from `context.response.match`. Example I gave to @michaelansel:

> in `robot.listen`, I returned an object like `{slackEnabled: true}`, then the middleware can check if `response.match.slackEnabled`

**Comment by rixlabs** [comment]
Another thing about documentation.

The link to the design patterns document is broken(404).
Maybe It's better to open another issue...

**Comment by technicalpickles** [comment]
I actually ran into this one while working on https://github.com/hubotio/hubot-for-hubot/pull/11 so it's still be good to tackle.
