### ISSUE TITLE
Document writing scripts in Javascript (and other languages)

### ISSUE THREAD

**Issue by technicalpickles** [hubotio/hubot#1082]
Hubot scripts can be written in Javascript in addition to Coffeescript. Hubot can actually load anything that nodejs can `require`. This isn't written down anywhere though.

cc @dev0n

**Comment by Dev0n** [comment]
Thanks @technicalpickles. It would be nice to load directories as well as single script files.

For example:

``` scripts/foo ``` (providing an index.js is present inside foo).

**Comment by cycomachead** [comment]
> For example:
> 
> scripts/foo (providing an index.js is present inside foo).

Yeah, this would be great as an addition, though it can also be done "manually".

I have this script which individually `require`s all scripts in subdirectories, but you could fairly easily modify it to use use `require(dir)`.

I'm fairly certain this script could just be turned into a package, as long as you can reliably get the location of the `scripts/` directory. (Which is be possible, but I haven't put much though into how brittle it would be.)

**Comment by technicalpickles** [comment]
This will be done as part of moving to Javascript cc https://github.com/hubotio/evolution/pull/4 @gr2m
