### ISSUE TITLE
Document private messages

### ISSUE THREAD

**Issue by technicalpickles** [hubotio/hubot#1098]
The Campfire adapter has supported this for awhile, but it's never been written down. https://github.com/github/hubot/blob/master/src/adapters/campfire.coffee#L73 will mark a message private if it was said in a locked room. The main reason to use this is to not post information about rooms posted in locked rooms elsewhere, for example, referencing a conversation outside of the room (on GitHub, email, logs, etc).

I proposed adding this concept to the slack adapter, but realized it's not actually documented https://github.com/slackhq/hubot-slack/pull/264

**Comment by technicalpickles** [comment]
I was also thinking to update the shell adapter to support `HUBOT_SHELL_PRIVATE` for marking all messages private for testing.

**Comment by yash14123** [comment]
Can I get some guidance for this?

**Comment by technicalpickles** [comment]
Documentation for writing scripts lives in `docs/scripting.md`. I think it could talk about private messages. Then adapters using it could be updated to talk about what conditions mark the thing as private.

**Comment by twellspring** [comment]
Just submitted #1161 which documents robot.messageRoom for sending to arbitrary rooms or to a private user.  Might this help here?
