### ISSUE TITLE
Way to run a matching script last

### ISSUE THREAD

**Issue by ngawor** [hubotio/hubot#1223]
We have a script that we want to run only after all other scripts have failed to match.  Right now, the code uses catchAll to look at the content, do some evaluation, and then decide whether or not to run.  The problem with the catchAll approach is that middleware listeners run for everything, and in some cases the content of the middleware listeners context/response is empty (for instance text is empty).

A better approach would seem to be to use a matching function (as opposed to a regex or catchAll) to determine whether or not to match.  The problem is that we only want to run this if nothing else has matched.  

So:

1) Is it expected that middleware listeners would run on catchAll and that certain parts of their content would be undefined?

2) Is there a way to order scripts so that our matching function would only be run after everything else failed to match?

@michaelansel

**Comment by michaelansel** [comment]
Interesting question! I'm out for defcon right now, but I'll think on this when I get back.

**Comment by michaelansel** [comment]
So, this obviously got completely forgotten. I'm sorry about that. 😓 😭 

I think the key problem you are running into is that all message types go through the CatchAll flow (Enter, Leave, Topic, etc.) and not just TextMessages. If you have your middleware condition on `if msg instanceof TextMessage` (with `TextMessage` imported from [`message.coffee`](https://github.com/github/hubot/blob/master/src/message.coffee#L14) ), that should get you only fully-defined TextMessages.

Sorry for the delay on this :-(

**Comment by technicalpickles** [comment]
If I am reading the original question correctly, `robot.listen` should do exactly what you are looking for:  https://github.com/github/hubot/blob/master/docs/scripting.md#custom-listeners . It gives you a lot of control of when it matches or not.
