### ISSUE TITLE
Coffeescript Interpreter Oddities

### ISSUE THREAD

**Issue by Saelvarath** [hubotio/hubot#1224]
I'm writing a coffeescript script for hubot and I'm running into several problems. 
- Nested If statements are ignored completely, 
- Numbers are sometimes being arbitrarily interpreted as Strings.

I'm using the latest version of Coffeescript and If I run the exact same code on http://coffeescript.org/ or on other sites and apps these issues do not occur

**Comment by mose** [comment]
This sounds weird, can you provide some code example?

**Comment by Saelvarath** [comment]
Hello, 
Sorry for the delayed response, the code was stored on an laptop that died suddenly, I was only recently able to pull some of the files off of it.

I found and attached the version of the code that I got to work through restructuring the nested IF statements in the "#Rule of 10" section and explicitly casting all the Numbers that were randomly evaluating as Strings. I'll do some more digging through the old laptop tomorrow, if it deigns to boot up, and see if I can find the version that was giving me the trouble.

[Hubot L5R Roller (Latest).txt](https://github.com/hubotio/hubot/files/1221175/Hubot.L5R.Roller.Latest.txt)

## Retroactive documentation
Just so it's easier to look through; the script is designed replicate rolling dice in the Legend of the Five Rings RPG system.

rolled = The number of dice you will roll
kept = The number of rolled dice that you are allowed to add together to determine the total of the roll
bonus = a value (positive or negative) that will be added to the total of the kept dice

additional variables are for the eventual inclusion of other features of the system that didn't get added before we had to abandon Rocketchat and move to a different program.

### Rule of 10
Only ten dice are allowed to be rolled at once but it is often the case that your character will have bonuses that bring their rolled and kept dice above this limit. Rolled dice in excess of this limit are turned into kept dice until you are both rolling and keeping 10 dice, then extra dice get turned into a static bonus to the roll.
