### ISSUE TITLE
robot.send has no middleware?

### ISSUE THREAD

**Issue by vicboyv** [hubotio/hubot#1233]
I've been remotely logging my robot using the robot.receiveMiddleware and robot.responseMiddleware methods. This works well with robot.respond (receiveM...) and msg.reply/msg.send (responseM...). (msg = res = context)

However, doing robot.send won't be picked up by any middleware (even listenerMiddleware).

I tried using another msg/context as the object for the send method (msg.send instead of the more sensible robot.send), it registers a log but it mixes the old msg properties (such as the user) with the new message AND it doesn't actually send anything.

What if I modify the User property in the context message and call the send method?

Why isn't robot.send included in the middlewares, even the general listenerMiddleware?

**Comment by michaelansel** [comment]
Sounds like we just missed calling the response middleware stack in [robot.send](https://github.com/github/hubot/blob/master/src/robot.coffee#L541-L542).

**Comment by technicalpickles** [comment]
The fix here is updating [robot.send](https://github.com/github/hubot/blob/d18cdcb111028dcd42b295ce0ca537a783debb90/src/robot.coffee#L534-L542) to call the middleware stack similar to how [response.send](https://github.com/github/hubot/blob/d18cdcb111028dcd42b295ce0ca537a783debb90/src/response.coffee#L15-L22) does. There's a `runWithMiddleware` helper in Response that would need to be copied to robot, or maybe there's some opportunity for refactoring to have it only one place.

**Comment by timkinnane** [comment]
This seems like something to keep open and consider for a PR?

**Comment by 4470** [comment]
actually i have opened this server.uncertainly light switch off & duty hrs were over so i think  it remain in use
