### ISSUE TITLE
Hubot not loading example.coffee on Rocket Chat in Raspberry Pi

### ISSUE THREAD

**Issue by naokibeats** [hubotio/hubot#1236]
Hi, i am installing rocket chat on Raspberry Pi and i'm using hubot like this tutorial http://www.rototron.info/raspberry-pi-chat-server-with-hubot/ but when i modify the example.coffee and start hubot, it doesn't load the example.coffee. I tried to print something in the example.coffee to test it but hubot not show nothing.
Please help me, thanks

**Comment by mose** [comment]
Do you still need help about this or time passed was too long?
