### ISSUE TITLE
Hubot Spamming

### ISSUE THREAD

**Issue by steowens** [hubotio/hubot#1278]
So I had been doing some testing with a Hubot on a slack private message.  Now everytime I start hubot, it responds to the old conversations as though it were hearing the messages for the first time.

To reproduce use hubot with a slack adapter.  Set up some robot.hear and robot.respond statements.  Engage with hubot in a private chat, and get it to respond to your messages.

Now stop and restart hubot.  You will see that on restart everything it responded to in your previous chat will be responded to again.  This happens no matter how many times you start and stop hubot, even if you send it no further messages.

**Comment by mose** [comment]
I think this issue should be directed to hubot-slack project at https://github.com/slackapi/hubot-slack

**Comment by youhide** [comment]
this can be about brain? i don't know how this brain works...
you try disable that?
