### ISSUE TITLE
query: how to make post call with parameters to be passed as form-urlencoded

### ISSUE THREAD

**Issue by shahp00ja** [hubotio/hubot#1280]
as per doc, i'm trying to make a post call with parameters but it works if the end-point has content acceptance as raw body not as  urlencoded:

![image](https://cloud.githubusercontent.com/assets/12966925/21520790/493cc0fa-cd1d-11e6-926d-2b0d3dbaea59.png)

**My conversion:**
```  
data = JSON.stringify('json: {"parameter": [ {"name":"name", "value":"neha"}]}')

robot.http("https://midnight-train")
    .header('Content-Type', 'application/x-www-form-urlencoded')
    .post(data) (err, res, body) ->
      # your code here

````

Ex. cURL which works & requires to be posted from my hubot coffeescript:
```
curl -X POST "http://blah.com/job/test/build" --user username:password  --data-urlencode json='{"parameter": [ {"name":"name", "value":"neha"}]}'
```

Please help what change is required in syntax to make it work

**Comment by shahp00ja** [comment]
@technicalpickles : could you please help what syntax changes I need to make here

**Comment by mose** [comment]
I suspect it may work better with

    data = JSON.stringify({ json: '{"parameter": [ {"name":"name", "value":"neha"}]}' })

but you probably figured it since then :)

**Comment by p00j4** [comment]
thanks @mose however this is not working with content type  `urlencode`
```header('Content-Type', 'application/x-www-form-urlencoded')```

**Comment by p00j4** [comment]
I couldn't get it work. bot please reopen it 🎲

**Comment by oltruong** [comment]
Hi @p00j4 

adding `.header('Content-type', 'application/json')` in your request does not work?
