### ISSUE TITLE
Newbie Question About a Kik Adapter

### ISSUE THREAD

**Issue by Viper702** [hubotio/hubot#1287]
I have looked all over the Internet for an adapter for hubot on Kik. Am I overlooking something in regards to the fact that an adapter for Kik doesn't exist? Is it preferable to use webhooks on the Kik platform? I have seen that there was an adapter called hubot-kik that seems to have disappeared from the Internet. Maybe someone could explain how I would go about connecting a hubot hosted on Heroku to Kik, please? I've tried to follow several tutorials wanting me to use my pc and ngrok and I'm afraid I just don't follow these webhook tutorials at all. Thank you.

**Comment by mose** [comment]
Seems that there is a way using the microsoft botframework and the hubot adapter for it

- https://docs.microsoft.com/en-us/bot-framework/thirdparty-channels/channel-kik
- https://github.com/Microsoft/BotFramework-Hubot
