### ISSUE TITLE
Why do the hubot name/alias has to prefix the sentence for response ?

### ISSUE THREAD

**Issue by jadjay** [hubotio/hubot#1298]
I tried with campfire and other adapters, it look likes the name must prefix the sentence, if not it's like hubot doesn't listen.

And hear shouldn't be the solution :)

**Comment by mose** [comment]
In the current code it is not possible to have an empty prefix, but you can use a short one. 

If you set an alias with `export HUBOT_ALIAS='.'` or use `-l .` when launching hubot, you can use it as an alternative to calling the bot name, ie. `.help` instead of `hubot help`. But that alias can't be empty.

**Comment by michaelansel** [comment]
> And hear shouldn't be the solution :)

Why not? That is exactly the distinction between `hear` and `respond`: hear matches any regex, respond is `hear` + a required prefix (the bot name).

**Comment by technicalpickles** [comment]
@jadjay can you give an example of what you are trying to do where `hear` doesn't work? Or a case where you want commands to not be prefixed?

Off hand, I could imagine maybe having a message having multiple sentences, and wanting to reply to the second sentence, ie

> Something's going on with the bot. @hubot ping

**Comment by kavya05** [comment]
hey i have developed a bot for my company and the participants in the chat are just "bot" and the "employee" so its very annoying for the employee to mention bots name at the beginning of each sentence , is there a way where they can converse with the bot in regular manner without having to mention bots name on every conversation?
**its very urgent for me i'm reaching my deadlines so please help me out in this one**
example: 
employee: hubot show my storage space resources 
instead he should be able to say
employee: show my storage space resources.

**Comment by jadjay** [comment]
Yes that's my use use case @kavya05
