### ISSUE TITLE
How to daemonize hubot?

### ISSUE THREAD

**Issue by sessionstop** [hubotio/hubot#1299]
Hello,

I failed to daemonize hubot even I added the & at the end of the command.

Any ideas?

**Comment by youhide** [comment]
running on own server? or something like PaaS?

**Comment by abbshr** [comment]
pm2 is ok

**Comment by nORKy54** [comment]
exemple:

`[Unit]
Description=Hubot Jack
Requires=network.target
After=network.target

[Service]
Type=simple
User=hubot

Restart=always
RestartSec=10

ExecStart=/opt/rocketbots/Jack/bin/hubot rocketchat 

[Install]
WantedBy=multi-user.target
`

**Comment by technicalpickles** [comment]
@sessionstop could you share how you were trying to background hubot, and what was happening when you did it?

There shouldn't be any tricks to backgrounding hubot. The only thing I can think of that might throw things off is if you don't specify an adapter using `-a` argument or `HUBOT_ADAPTER` environment variable, it defaults to shell adapter.

**Comment by strugee** [comment]
@technicalpickles if you don't use a tool like `nohup` running just `hubot &` will cause SIGHUP to be sent to Hubot when the terminal is closed, which will probably kill it. That might've been what happened.

**Comment by sessionstop** [comment]
Hi guys, I made it, by using tmux, LOL. I'm using Ubuntu 16.04 Server LTS on a VPS. I just install tmux and then execute the commands:

1. tmux new -s hubot
2. HUBOT_SLACK_TOKEN=**YOUR-SLACK-TOKEN** ./bin/hubot --adapter slack
3. then execute ctrl + b, then press d to logout tmux while keep hubot running.

You can write a shell to "demonize" hubot. Hope this will help those who are in need.

**Comment by strugee** [comment]
@sessionstop you might find https://unix.stackexchange.com/a/89493/29146 helpful.

**Comment by sessionstop** [comment]
yes, screen is an alternative. As @abbshr said, pm2 seems to be a better solution. But, I am not node developer, so this may not be my favorite choice. :-D

**Comment by strugee** [comment]
Tbh I never quite understood why things like pm2 existed when most Linuxes come with a perfectly workable init system which usually will do a much better job managing services (and service dependencies!) than random service managers on npm that don't integrate well with their host. But this is getting a little off-topic, so I'll shut up ;)
