### ISSUE TITLE
How to pass the adapter directly for Robot?

### ISSUE THREAD

**Issue by VictorQueiroz** [hubotio/hubot#1305]

**Comment by mose** [comment]
Can you provide a little bit more context? A use-case maybe?

**Comment by technicalpickles** [comment]
Just taking a guess, but currently you specify the adapter on the command line, ie `hubot -a slack`. The `robot` object you have in scripts is [`Robot`](https://github.com/github/hubot/blob/master/src/robot.coffee), which does have an adapter object. I think it will make sense to consider it for v3 (maybe combining with https://github.com/github/hubot/issues/858), but right now `robot.adapter` is pretty tied to hubot's startup so you can't just swap it out.
