### ISSUE TITLE
Consolidate officially supported repos into a single organization

### ISSUE THREAD

**Issue by bkeepers** [hubotio/hubot#1327]
[From the roadmap](https://github.com/github/hubot/blob/master/ROADMAP.md):

> - [ ]  Consolidate all officially supported Hubot projects into a single GitHub organization. This will include github/hubot and a handful of supported scripts, but will not include all community scripts in https://github.com/hubot-scripts

Ideally, we would move everything to @hubot. The challenge is that @hubot is a User account, not an Organization, and it is _heavily_ used internally at GitHub. I will start working on deprecating it internally, but it will likely be a several month long process, so I don't think we should wait to start consolidating repositories.

- [x] Decide on interim name for the organization. Currently: @hubotio
- [x] Create list of packages from https://github.com/hubot-scripts that should be transferred
- [x] Transfer repositories
  - [x] https://github.com/github/hubot
  - [x] https://github.com/github/generator-hubot
  - [x] ~~https://github.com/github/hubot.github.com~~ (currently private)
- [x] Transfer supported scripts
  - [x] [hubot-scripts/hubot-diagnostics](https://github.com/hubot-scripts/hubot-diagnostics)
  - [x] [hubot-scripts/hubot-help](https://github.com/hubot-scripts/hubot-help)
  - [x] ~~[hubot-scripts/hubot-heroku-keepalive](https://github.com/hubot-scripts/hubot-heroku-keepalive)~~
  - [x] ~~[hubot-scripts/hubot-google-images](https://github.com/hubot-scripts/hubot-google-images)~~
  - [x] ~~[hubot-scripts/hubot-google-translate](https://github.com/hubot-scripts/hubot-google-translate)~~
  - [x] ~~[hubot-scripts/hubot-pugme](https://github.com/hubot-scripts/hubot-pugme)~~
  - [x] [hubot-scripts/hubot-redis-brain](https://github.com/hubot-scripts/hubot-redis-brain)
  - [x] [hubot-scripts/hubot-rules](https://github.com/hubot-scripts/hubot-rules)
  - [x] ~~[hubot-scripts/hubot-shipit](https://github.com/hubot-scripts/hubot-shipit)~~
- [x] Notify package authors in @hubot-scripts that the org is being deprecated
- [x] Rename @hubot-scripts to @hubot-archive
- [x] transfer [github/hubot-scripts](https://github.com/github/hubot-scripts) to @hubot-archive

What else do we need to consider?

**Comment by technicalpickles** [comment]
The hubot generator, which is in the documentation: https://github.com/github/generator-hubot

cc https://github.com/github/hubot/pull/1328 about its fate

**Comment by bkeepers** [comment]
I added the default scripts that are included in the generator too. We might want to pair those down when we work on the generator.

**Comment by bkeepers** [comment]
I transferred a few of the repos to @hubotio. Unless there's any opposition, I'd like to go ahead and move the main github/hubot repository this week. GitHub should handle all of the redirects, so I don't expect any issues.

I also updated a couple items on the list:

> - [ ] Rename @hubot-scripts to @hubot-archive
> - [ ] transfer [github/hubot-scripts](https://github.com/github/hubot-scripts) to @hubot-archive

@technicalpickles, does that sound ok? Is anyone else maintaining all of those scripts?

**Comment by technicalpickles** [comment]
That looks good to me.

As far as anyone maintaining, the list of 'teams' on the org are at https://github.com/organizations/hubot-scripts/settings/teams ... most of them seem to be repo specific.

There is a [owners team](https://github.com/orgs/hubot-scripts/teams/owners), which gives them access to all the repos and the ability to create new repos, maintain existing ones, etc. I have not really been keeping up on notifications for that org, so I'm not sure who is active aside from who has already been active on the main repo and in chat (myself, bkeepers, michaelansel):

- @patcon
- @alindeman
- @therealklanni
- @jjasghar

**Comment by patcon** [comment]
Though I love the idea of being in a quantum state, I'd say I'm inactive ;)

**Comment by therealklanni** [comment]
Have we issued official notice to the maintainer/owners of the various scripts on @hubot-scripts? I have migrated (or at least started doing so) the remaining ones that I owned.

**Comment by gr2m** [comment]
I would argue from the remaining scripts:

- hubot-scripts/hubot-heroku-keepalive
- hubot-scripts/hubot-google-images
- hubot-scripts/hubot-google-translate
- hubot-scripts/hubot-pugme
- hubot-scripts/hubot-rules
- hubot-scripts/hubot-shipit

I would move `hubot-rules` and leave out the rest. 

- the problem with `hubot-heroku-keepalive` is that heroku no longer has free instances. We could look into making [now.sh](https://zeit.co/now) the recommended deploy target instead.
- `hubot-google-images` logs an error by default
- `hubot-google-translate`  fails with an error `ERROR SyntaxError: Invalid JS code`
- `hubot-pugme` and `hubot-shipit` return URLs which don’t work.

**Comment by patcon** [comment]
> `hubot-heroku-keepalive`: Heroku no longer has free instances. We could look into making now.sh the recommended deploy target instead.

Not to be pedantic, but is it not still useful for ppl who want to keep hubot alive for the given 18 hours a day? I still use it :)

**Comment by gr2m** [comment]
@patcon you can still add it to your app, no problem. It just wouldn’t be one of the scripts we’d install by default when you use the hubot app generator

**Comment by therealklanni** [comment]
Don't tell Heroku, but I still use Free instances. Shhh.

**Comment by technicalpickles** [comment]
> Notify package authors in https://github.com/hubot-scripts that the org is being deprecated

Think we can consider that done: https://github.com/hubot-scripts/packages

>DEPRECATED
>
>If you would like to have your Hubot Script Package grouped under the Hubot Scripts organization (so it can be found easily by others), this used to be the place to open an issue to get it added to this organization.
>
>Instead, you should keep your package on your own user or organization and publish it to [NPM](https://www.npmjs.com/)

---

> Rename @hubot-scripts to https://github.com/hubot-archive

Done.

---

> transfer [github/hubot-scripts](https://github.com/github/hubot-scripts) to @hubot-archive

It's already been archived. If someone at GitHub wants to transfer it, please ping me if there isn't access to do so.
