### ISSUE TITLE
Support loading an adapter object

### ISSUE THREAD

**Issue by rqc** [hubotio/hubot#1341]
Hi,

`loadAdapter()` as it is implemented [here](https://github.com/github/hubot/blob/master/src/robot.coffee#L467-L485) does not support loading an adapter object that is created elsewhere and passed as an argument. I've found that this is very useful when creating tests for adapters and robots alike. So I've had to override the method like using an approach like this:
```coffeescript
Hubot.Robot::loadAdapter = (adapter) ->
  @adapter = adapter
```
In order to have more control.

Would you consider adding extra support for this scenario on `loadAdapter()`?

Thanks!

**Comment by mose** [comment]
It looks like a good and low-risk idea. Do you have some published example test code that takes advantage of this feature? Just curious.

**Comment by technicalpickles** [comment]
I think this would be a good candidate for [the evolution process](https://github.com/hubotio/evolution/)
