### ISSUE TITLE
Adding ML features

### ISSUE THREAD

**Issue by matteoredaelli** [hubotio/hubot#1351]
It would be nice to add some ML features using tensorflow or others.. see https://chatbotsmagazine.com/contextual-chat-bots-with-tensorflow-4391749d0077

**Comment by mose** [comment]
Certainly, in a more distant future. But Hubot is a framework, it has an ecosystem of 2k+ plugins. Changing the way messages are processed would not come as a simple move.

But it would be totally possible, I guess, to create a plugin that introduces advanced syntactic analysis in a middleware.

**Comment by bkeepers** [comment]
Hey @matteoredaelli, thanks for the suggestion!

If you have thoughts on how you would want to see these features implemented, check out the [evolution](https://github.com/hubotio/evolution) process. ML features are not currently a priority, but they are of great interest to me personally, so I'd love to see a proposal and some experiments.
