### ISSUE TITLE
Hubot should still respond to private messages when prefixed with its name

### ISSUE THREAD

**Issue by patcon** [hubotio/hubot#1356]
I'm trying to introduce our hubot to new people, and it's come up as a friction point that hubot is silent when you try to communicate with it in private just the same as you do in public. This private space seems exactly where new persons would try to get comfortable with a new thing, so it seems very important that it's not needlessly confusing :)

Would this be something that were simple to remedy?

cc @suchthis @dcwalk

**Comment by technicalpickles** [comment]
I know I've definitely run into this myself. I suspect this may be adapter-specific behavior though. Here's what Slack does: https://github.com/slackapi/hubot-slack/blob/d2be93748e193e5012a7cd0cc44e08bbb4d22c13/src/bot.coffee#L165-L168

It is prepending incoming DMs with the bot's name, so that `robot.respond` listeners will match for it. I think you could make the case that might not actually be desirable, since it leads to what you are seeing. Changing that behavior would be semantically different though.

It might be possible to use [receive middleware](https://github.com/hubotio/hubot/blob/master/docs/scripting.md#receive-middleware) to adjust the incoming text to remove the extra robot name.

**Comment by patcon** [comment]
Ah wonderful! thanks so much @technicalpickles :)

I'll open an issue with the slack adapter. And the middleware suggestion is _golden_.

So to confirm, it's not in any official hubot docs that this is encouraged behavior in private messages?

(I'm considering @mention-ing other adapter maintainers in here, to get a sense of whether this is desired pattern, or an anti-pattern that somehow just stuck :) )

**Comment by technicalpickles** [comment]
I am not as familiar with the IRC adapter, but it seems to be doing it too: https://github.com/nandub/hubot-irc/blob/master/src/irc.coffee#L293-L294

**Comment by patcon** [comment]
cc: @KasperDeng [`Hubot-WeChat`](https://github.com/KasperDeng/Hubot-WeChat)
cc: @geekgonecrazy [`hubot-rocketchat`](https://github.com/RocketChat/hubot-rocketchat)
cc: @markstory [`hubot-xmpp`](https://github.com/markstory/hubot-xmpp)
cc: @loafoe [`hubot-matteruser`](https://github.com/loafoe/hubot-matteruser)
cc: @grantmd [`hubot-slack`](https://github.com/slackapi/hubot-slack)
cc: @nandub [`hubot-irc`](https://github.com/nandub/hubot-irc)
cc: @rbergman [`hubot-hipchat`](https://github.com/hipchat/hubot-hipchat)

Any thoughts: How do your adapters handle private/direct messages, and would you be willing to standardize on accommodating same command syntax in public and private format? (If you'd like to just +1, I'll open a issue stub in your queue, and it'd be amazing it your could link to relevant code for whoever picks it up)

**Comment by markstory** [comment]
The xmpp adapter lets you enable prefixing through the [HUBOT_XMPP_PM_ADD_PREFIX](https://github.com/markstory/hubot-xmpp/blob/bbe080ce6e3dabeebce57485f3d1147a8f74da23/src/xmpp.coffee#L42) environment option.

**Comment by geekgonecrazy** [comment]
The rocketchat adapter we use an environment variable `RESPOND_TO_DM` to enable / disable responding to DM's.  But if the bot is not mentioned we automatically add prefix with the bots name.

https://github.com/RocketChat/hubot-rocketchat/blob/master/src/rocketchat.coffee#L184

**Comment by patcon** [comment]
I really like the RocketChat approach @geekgonecrazy (easy default), so I've submitted a similar PR to `hubot-slack`. Thanks a bunch!
