### ISSUE TITLE
Listener middleware not called for catchAll listener

### ISSUE THREAD

**Issue by rophy** [hubotio/hubot#1362]
# Version

- hubot@2.19.0

# Problem

Hubot supports populating contents in `message` object through [middlewares](https://github.com/hubotio/hubot/blob/master/docs/scripting.md#listener-middleware), but it seems the contents are lost in `catchAll` handler.

# Reproduce Steps

scripts/example.coffee:
```coffeescript
# Description:
#   Test listener and catchAll.
# 
module.exports = (robot) ->
  robot.catchAll (res) ->
    res.reply res.message.secret
  robot.respond /test/, (res) ->
    res.reply res.message.secret
  robot.listenerMiddleware (context, next, done) ->
    context.response.message.secret = 'hello'
    next()
```

Testing
```
C:\Users\rophy\git\hubot-secret>bin\hubot
up to date in 1.074s
hubot-secret> hubot-secret test
hubot-secret> Shell: hello
hubot-secret> hubot-secret abcabc
hubot-secret> Shell: undefined
```

**Comment by timkinnane** [comment]
In the test you're loading a file called config.coffee, but your src script is secret.coffee. Is that just a typo?

Also worth noting that hubot-test-helper uses mock classes and methods that aren't exactly alike to the original hubot. It's good for basic listener tests but falls short in some ways especially when testing middleware, so it may not be a fault of your code, but the test. 

Have you tried prompting this interaction manually in normal hubot, for example using the shell adaptor?

**Comment by rophy** [comment]
@timkinnane I was trying to make a simple reproducing case, both the typo and the usage of hubot-test-helper do not affect the result.

To avoid complicating things, I have updated the reproduce sample, thanks for the response.

**Comment by timkinnane** [comment]
OK actually I think I know why this isn't working anyway. From the docs: "Listener middleware inserts logic between the listener matching a message and the listener executing" - catch all fires when no listeners match, so the listener middleware would never be called in this case. You should try it with `robot.receiveMiddleware` instead.

**Comment by rophy** [comment]
Worked exactly as @timkinnane said, thanks so much!

**Comment by technicalpickles** [comment]
@timkinnane's suggestion to use a receive middleware is a good one, but I think this might be a bug, or if not, just a use case that wasn't considered.

Here's some of the relevant code:

- `robot.catchAll` https://github.com/hubotio/hubot/blob/master/src/robot.js#L214-L233
- `robot.processListeners` when a listener wasn't matched, so it `receive`s a new catchall message: https://github.com/hubotio/hubot/blob/master/src/robot.js#L331-L340
- `robot.receive` processes with listeners

Having listed this out, I am wondering if the listenerMiddleware @rophy wrote is not actually matching for the catchAll for some reason.

cc @michaelansel as my go to middleware expert 😅

**Comment by timkinnane** [comment]
@technicalpickles are you saying listenerMiddleware **should** be called prior to the catchAll, even if there's no listeners?

I can see why that might be helpful sometimes, but if it not doing so currently is a bug, it might confuse people and break stuff if that's "fixed", because I would assume there's scripts out there counting on the middleware not firing unless actual listeners are called (not counting catchAll).

**Comment by technicalpickles** [comment]
I'm saying that the [catchAll is itself a listener](https://github.com/hubotio/hubot/blob/master/src/robot.js#L214-L233), so listener middleware should run as part of calling the catchAll.

>  if it not doing so currently is a bug, it might confuse people and break stuff if that's "fixed"

Good thing we are adopting semantic versioning and planning to release more often then 😅

**Comment by timkinnane** [comment]
Good stuff. Well this tickets original question is answered, but if we're keeping it open to resolve the bug it's raised, can we modify the title to something like "Listener middleware not called for catchAll listener"?
