### ISSUE TITLE
npm warning when using node 4.8.3 with hubot-3.0.0

### ISSUE THREAD

**Issue by technicalpickles** [hubotio/hubot#1363]
I just tried updating a bot I made last week with hubot 2.19.0 to hubot@next (ie 3.0.0), and I was getting this warning:

```
$ npm install --save hubot@next
npm WARN engine hubot@3.0.0: wanted: {"node":">4","npm":">2"} (current: {"node":"4.8.3","npm":"2.15.11"})
```

Maybe the node version needs to be `>= 4`?

cc @gr2m https://github.com/hubotio/evolution/pull/4

**Comment by gr2m** [comment]
looks like a problem with npm@2, I don’t see the error in npm@3 or beyond. I’m looking into it.

**Comment by gr2m** [comment]
can you try `npm install --save hubotio/hubot#1363/engines-fix`? PR: https://github.com/hubotio/hubot/issues/1364

**Comment by technicalpickles** [comment]
@gr2m that fixes it, thanks!
