### ISSUE TITLE
How to get JSON output with Coffeescript?

### ISSUE THREAD

**Issue by Akhilesh-Anb** [hubotio/hubot#1365]
Hi,

I have integrated Hubot with elasticsearch and slack.
When we are querying on the API, we are getting the output in JSON format when we use postman.

When we are querying from slack with coffeescript,we are getting plain output.
Here is the code

```
showHealth = (msg) ->
      msg.send("Getting the health for the cluster: ")
      msg.http("http://show-acc.com/_cluster/health/")
        .get() (err, res, body) ->
          lines = body.split("\n")
          header = lines.shift()
          list = [header].concat(lines.sort().reverse()).join("\n")
          msg.send("/code \n ```#{list}```")
```

This is printing me plain output in slack. 
Could you please anyone help me how to change the code to print the output as JSON format?

**Comment by androidfanatic** [comment]
1. Specify a header when requesting for JSON

       msg.http("http://show-acc.com/_cluster/health/")
          .header('Content-Type', 'application/json')
          .get() (err, res, body) ->
           ....

2. Instead of just sending a message using msg.send, you will have to upload a snippet on slack

You can access the slack client using `msg.robot.adapter.client` and then upload a code snippet to slack.

       msg.robot.adapter.client.web.files.upload("code-block", {
         "content": "<your-code-snippet>",
         "filetype": "auto",
         "title": "code-block",
         "channels": msg.envelope.room
       }, (err, res_slack) => {
         if (err) { 
           console.log(err);
         } else {
           console.log("Code block uploaded")
         }
       });

**Comment by technicalpickles** [comment]
The suggestions @androidfanatic should help.
