### ISSUE TITLE
Unable to make POST request: Hubot scripts & Gitlab api

### ISSUE THREAD

**Issue by PadmaChannal** [hubotio/hubot#1369]
HI,

I am trying to invoke a Gitlab api using POST request in my hubot scripts:

data = JSON.stringify({
	'PRIVATE-TOKEN': 'xxx'
    })

     module.exports = (robot) ->
      robot.hear /could you deploy/i,(res) ->
      res.robot.http("https://gitlab.example.com//api/v4/projects/11/jobs/16863/retry")
      .header('Accept', 'application/json')
      .post(data) (err, res, body) ->
      # err & response status checking code here

      if response.getHeader('Content-Type') isnt 'application/json'
        res.send "Didn't get back JSON :("
        return

      resbody = null
      try
        resbody = JSON.parse body
      catch error
       res.send "Ran into an error parsing JSON :("
       return

Cant make a Post request using Coffee script.

**Comment by mose** [comment]
Can you try with 

```
 module.exports = (robot) ->
  robot.hear /could you deploy/i, (res) ->
    robot.http("https://gitlab.example.com//api/v4/projects/11/jobs/16863/retry")
    .header('Accept', 'application/json')
    .header("PRIVATE-TOKEN", @apikey)
    .post() (err, response, body) ->
      # err & response status checking code here

      if response.getHeader('Content-Type') isnt 'application/json'
        res.send "Didn't get back JSON :("
        return

      resbody = null
      try
        JSON.parse(body)
      catch error
        res.send "Ran into an error parsing JSON :("
```

Notes:
- coffeescript is very picky on indentation
- you had a confusion between the `res` from `robot.hear` and the `res` from http response
- the token has to be passed in header and not in the post body as shown on https://gitlab.msu.edu/help/api/jobs.md#retry-a-job

**Comment by PadmaChannal** [comment]
Hi Mose, Thank you for your reply.
I tried your code snippet:
-By putting Private token in header
and also tried technicalpickles solution in https://github.com/hubotio/hubot/issues/1060 
-With respect to res and robot.hear
I am not sure why the solution didn't work. However I tried 
   
    # Author:
    #   Padma Channal

 module.exports = (robot) ->
  robot.respond /Deploy em$/i,(res) ->
	  room = 'playing_with_hubot'
	  robot.messageRoom room, " Deploying ..."
	  robot.http("https://example.com//api/v4/projects/11/jobs/17359/retry")
    .header('PRIVATE-TOKEN', 'XXX')
    .post() (err, res, body) ->
      if err
        res.send "Encountered an error :( #{err}"
        return
	  res.send "Got back the body --> #{body}"  
 
I removed header:
  .header('Accept', 'application/json')

since I did not have to process JSON body back.

This works.

Thank you for your time. I appreciate it.

**Comment by PadmaChannal** [comment]
Unable to read any 'body' from the HTTP request made in Hubot Script.



   module.exports = (robot) ->
   robot.respond /dep$/i,(msg) ->
	  room = 'playing_with_hubot'
	  robot.messageRoom room, " I am monkey, still evolvoing "
	  msg.send 'Help me understand you'
	  
	  robot.http("https://example.org/api/v4/projects/11/pipelines?per_page=100")
    .header('PRIVATE-TOKEN', 'xxxx')
    .get() (err, res, body) ->
      if err
        robot.messageRoom room "Encountered an error :( #{err}"
      if res.statusCode isnt 200
        res.send "Request didn't come back HTTP 200 :("
        
	  robot.messageRoom room "Got back the body --> #{body}"
	  robot.messageRoom room, " Now its getting complicated! "
	  msg.send 'Too much'
