### ISSUE TITLE
response.rawHeaders is defined but headers dictionary is empty

### ISSUE THREAD

**Issue by lutrampal** [hubotio/hubot#1380]
Hi,

Writing a condition to check if a response contained JSON I came across this problem.
After an HTTP call (using any HTTP method), `response.rawHeaders` contains data, including Content-Type but `response.headers['Content-Type']` is undefined. In fact the whole dictionary `response.headers` contains no key at all.
A workaround for me was to use `/Content-Type,application\/json/.test(res.rawHeaders)` but that's not very clean...

Also, looking for a fix I noticed although https://github.com/hubotio/hubot/pull/1332 is closed, the documentation still uses the old `getHeader()` method.

**Comment by klinux** [comment]
Key-value pairs of header names and values. Header names are lower-cased.
