### ISSUE TITLE
Rate limited

### ISSUE THREAD

**Issue by andreash92** [hubotio/hubot#1384]
I am getting a message `info: Rate limited, will retry 9 seconds` and i don't know where it comes from. I'm running hubot in Slack and deployed locally. 

Any ideas?

**Comment by mchristensen76** [comment]
Running the following command indicates its coming from the @slack/client module:

`grep -R "Rate limited, will retry" *`

node_modules/@slack/client/lib/clients/transports/call-transport.js:  client.logger('info', 'Rate limited, will retry %s seconds', headerSecs);

**Comment by andreash92** [comment]
thanks for that command! 

> If you do a lot of call's to robot.brain.set you'll run into the issue reported above. The source of the problem is in the file hubot-slack/src/bot.coffee, line 58.

makes sense now, because i started seeing this error when i started using the `robot.brain.set/get`

**Comment by dodgepong** [comment]
For future Googlers, I found this searching for `info: Rate limited, will retry 10 seconds`, and I had several calls to `robot.brain.set` in my code. This issue was fixed in [hubot-slack v4.4.0](https://github.com/slackapi/hubot-slack/releases/tag/v4.4.0), and upgrading to that version fixed the issue for me. I no longer have my log spammed with timeout messages and my bot no longer randomly stops responding to requests.

**Comment by santimendoza** [comment]
> For future Googlers, I found this searching for `info: Rate limited, will retry 10 seconds`, and I had several calls to `robot.brain.set` in my code. This issue was fixed in [hubot-slack v4.4.0](https://github.com/slackapi/hubot-slack/releases/tag/v4.4.0), and upgrading to that version fixed the issue for me. I no longer have my log spammed with timeout messages and my bot no longer randomly stops responding to requests.

That's weird. I am using v.4.5.5 and receiving that console log when initiating my bot. Any ideas?

**Comment by 2969266** [comment]
Still get `info: Rate limited` against hubot-slack v4.6.0

**Comment by sankalp-khare** [comment]
And on `4.7.2` as well.

**Comment by ThilekSilvadorai-TomTom** [comment]
`4.8.0` as well after using `hubot-redis-brain`

**Comment by zdtsw** [comment]
on v4.8.1, no hubot-redis-brain enabled, same message.

**Comment by magander3** [comment]
Also on v4.8.1 and getting the same message. Did anyone find a solution ?

**Comment by slotdawg** [comment]
Also on v4.9.0...

**Comment by Deepak-DSS-L3** [comment]
It is still there , we have a org size of 40K plus , any solutions yet ?

**Comment by chrisbolt** [comment]
https://github.com/slackapi/hubot-slack/issues/621

`API_PAGE_SIZE=1000` can reduce the messages, `DISABLE_USER_SYNC=true` will fix.
