### ISSUE TITLE
Document logging

### ISSUE THREAD

**Issue by strugee** [hubotio/hubot#1388]
We should document exactly what `robot.logger` is (it's only mentioned in passing in an example). Also we should document `HUBOT_LOG_LEVEL`.

**Comment by timkinnane** [comment]
Would like the evolution process to maybe consider an update to the underlying log package. Maybe using Winston, with Morgan for auto logging HTTP requests, e.g: http://tostring.it/2014/06/23/advanced-logging-with-nodejs/

But yeah, in the interim, docs would be good.

**Comment by strugee** [comment]
stalebot: shut up. This is so obviously still an issue.

Can someone seriously turn that thing off? It makes sense in high-traffic repositories but this one just... isn't. It's stupid and wastes people's time.

**Comment by timkinnane** [comment]
This project is abandoned. I tried keeping stale bot away from a couple of my issues but it just keeps coming back and no one is reviewing them anyway. I've messaged the core team through slack and no one responds. The community is still supporting each other and some of the external contributors with limited access are still approving PRs from time to time, but there's no one at the reigns. There's some murmurs of waiting for direction from higher ups at GitHub, but it's very disappointing that they've not even tried to communicate with the community or respond to basic requests like turning off stalebot, which is just carpet bombing legitimate issues.

**Comment by strugee** [comment]
@timkinnane time for a community fork maybe? Idk

**Comment by timkinnane** [comment]
Indeed. I've been working on one, but I've refactored a lot without updating docs, so it's not ready for mainstream consumption. I'll email you.

**Comment by strugee** [comment]
Neat. FWIW I just thought of "Nubot" as a fun fork name (play on "new") but I can't tell if it's stupid or not because it's 1:40 AM here :thumbsup:

**Comment by timkinnane** [comment]
Haha, yep, that's what I called it.

**Comment by D-cm** [comment]
Hola de 10

**Comment by technicalpickles** [comment]
Hey, activity: https://github.com/hubotio/hubot/pull/1581

This is a good idea. https://github.com/hubotio/hubot/blob/master/docs/scripting.md would be the place to include it.

`robot.logger` uses https://www.npmjs.com/package/log

**Comment by joeyguerra** [comment]
Hubot logger is now an instance of [pino](https://getpino.io/)
