### ISSUE TITLE
E2389b2659

### ISSUE THREAD

**Issue by CharredCharry** [hubotio/hubot#1392]
{"sig":"9798324a04842000d9b20de2389b2659{"sig":"9798324a04842000d9b20de2389b2659","payload":{"success":false,"data":null,"response_code":500,"server_code":"BINGOSECURE_VALIDATEPARAMS_INVALID","etraces":[{"code":500,"server_code":"BINGOSECURE_VALIDATEPARAMS_INVALID","message":"param validation error. [\"Invalid city_id\",\"Invalid win_amount\"]"}]}}{"success":false,"data":null,"response_code":500,"server_code":"BINGOSECURE_VALIDATEPARAMS_INVALID","etraces":[{"code":500,"server_code":"BINGOSECURE_VALIDATEPARAMS_INVALID","message":"param validation error. [\"Invalid city_id\",\"Invalid win_amount\"]"}]}}

**Comment by mose** [comment]
looks like spam, closing.
