### ISSUE TITLE
How to remove default scripts? ie shipit etc?

### ISSUE THREAD

**Issue by MichaelMallett** [hubotio/hubot#1397]
When I type @hubot help on my bot in Slack I get a whole heap of commands, none of which are useful to me. How do I remove all of these if they are included in the node module?

**Comment by Nothingtoloose** [comment]
The scripts can be easily deactivated by modifying the "external-scripts.json" file.

Just remove the names of the plugins in the file and restart Hubot.

**Comment by technicalpickles** [comment]
In addition to what @Nothingtoloose suggested, you'll also want to remove them from `package.json`.
