### ISSUE TITLE
Broken scripts shipped with installation

### ISSUE THREAD

**Issue by rgomez90** [hubotio/hubot#1400]
There are some scripts, like the **google-translate** one, that are completely broken. In this case the script still uses the old `translate.google` instead of the actual Cloud API. 

There were also some PR to the project without any reaction.

Would be great if such scripts are removed and no more available "out of the box".

**Comment by ScrumpyJack** [comment]
List of scripts not working that are shipped with hubot:

shipit (ironically)
google-translate (requires API token)
google-images (requires API token)
pugme (broken image URLs)

any more?

**Comment by rgomez90** [comment]
maps as well (at least one part) - requires API Token too

**Comment by technicalpickles** [comment]
This was fixed at some point. There's only a handful of scripts included now: https://github.com/hubotio/generator-hubot/blob/16d2c816add04f7bbd36d0efc28c0350f23f7f90/generators/app/index.js#L131-L137
