### ISSUE TITLE
Not getting script respond from hubby

### ISSUE THREAD

**Issue by PacMacCock** [hubotio/hubot#1401]
So I making a post request to hubot-adapter I don't know why it is not trigger any scripts. I don't actually have a chat client. There's no user, id, room. 

     let Adapter, Robot, TextMessage, User, TextListener;
     try {
       ({Robot,Adapter,TextMessage,User, TextListener} = require('hubot'));
     } catch (error) {
        const prequire = require('parent-require');
      ({Robot,Adapter,TextMessage,User, TextListener} = prequire('hubot'));
     }

      class Sample extends Adapter {

       constructor() {
        super(...arguments);
        this.robot.logger.info("Constructor");
        }

         send(envelope, ...strings) {
           return this.robot.logger.info("Send");
         }

       reply(envelope, ...strings) {
          return this.robot.logger.info("Reply");
       }

       run() {
           this.robot.router.post('/app', (req, res) => {
           const data = req.body.test;
           const message = new TextMessage({}, data, 'MSG-001');
           this.robot.receive(message);
           return res.json({message: message});
        });

        this.emit('test', this.test);

    this.robot.logger.info("Run");
    this.emit("connected");
    const user1 = new User(1001, {name: 'Sample User', room: "shell"});
    const message = new TextMessage(user1, 'test', 'MSG-001');

    //console.log(message);
    return this.robot.receive(message);
      }
     }

    exports.use = robot => new Sample(robot);

All I want is to trigger the script below from a post request. 

      module.exports = (robot) => {

          robot.hear(/test/i, (res) => {
           console.log('testing');
         res.send("testing from script");
         });
      }

**Comment by kavya05** [comment]
![image](https://user-images.githubusercontent.com/30457237/36364808-5ad4552e-156c-11e8-8903-97654412e7b1.png)
try adding a listener to your program

**Comment by joh6nn** [comment]
closing this as stale
