### ISSUE TITLE
Can we please get rid of the SIGTERM catch?

### ISSUE THREAD

**Issue by hparadiz** [hubotio/hubot#1403]
I had to comment out these 3 lines so that my bot can do some custom clean up code with it's own SIGTERM and SIGINT.

https://github.com/hubotio/hubot/blob/8b0b8a9ba80e6d65df2e644b106c43d4b309d01f/bin/hubot.js#L84

Can we please get rid of this? As far as I can tell it's not actually doing anything other than exiting with a Status code 0 but it is preventing me from writing my own handler.

**Comment by charltonstanley** [comment]
It is a bit unfortunate that this was removed. I'm running hubot in a docker container. When I run `docker stop` to stop the container, it sends `SIGTERM` to the container which is ignored by hubot. 10 seconds later, docker does a `SIGKILL` to stop the container ungracefully.

**Comment by joeyguerra** [comment]
My thinking on this is that the responsibility of handling process related signals is outside of Hubot's core responsibilities. And this same code (`process.on('SIGTERM')`) can be added as a user defined script in the `scripts` folder that gets loaded with other scripts if the instance owner wanted to handle the signal.
