### ISSUE TITLE
npm WARN hubot-help@0.2.2 requires a peer of coffee-script@^1.12.6 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by langsky** [hubotio/hubot#1404]
how should i do? i installed coffee-script@1.12.7 but this need 1.12.6? why can`t i use 1.12.7?

**Comment by zahiryahya1** [comment]
I had the same problem but it turns out i was running the command in the wrong directory. maybe you are doing the same?

**Comment by richardwlu** [comment]
@langsky Did you happen to figure this out?

@zahiryahya1 I am having a similar issue: `hubot-help@0.2.2 requires a peer of coffee-script@^1.12.6 but none is installed. You must install peer dependencies yourself.`. I am running in the correct directory though. Would you happen to have any ideas on this?

**Comment by ociata** [comment]
I resolved this warning by manually adding `"coffee-script": "^1.12.6"` to package.json. Not sure why it is not there by default though.
