### ISSUE TITLE
Deploy Hubot 3.x to NPM?

### ISSUE THREAD

**Issue by jwbennet** [hubotio/hubot#1406]
Hello,

I was excited to see that version 3 had come out but I didn't see it available in NPM.  If I go to https://www.npmjs.com/package/hubot it reports the latest version is still 2.19.0.  Any thoughts on getting the newer versions deployed out there?

Thanks!

**Comment by atomanyih** [comment]
idg why this is so hard for some packages but in the meantime you can just point your `package.json` at the tag:

```
{
// ...
  "devDependencies": {
// ...
    "hubot": "hubotio/hubot#v3.0.1"
  }
}
```

**Comment by strugee** [comment]
@jwbennet @atomanyih it already _is_ on npm. It's under the `next` dist-tag, so you can get it with either `npm install --save hubot@3` or `npm install --save hubot@next`

**Comment by MattSFT** [comment]
Since there is a 3.0.1 stable release, is there a reason not to deploy that npm as the latest hubot to npmjs?

**Comment by technicalpickles** [comment]
The 3.x series has been promoted to `latest` 🎉
