### ISSUE TITLE
Cannot deploy Hubot on Heroku - npm file breaks build

### ISSUE THREAD

**Issue by uCreateStudio** [hubotio/hubot#1409]
I'm trying to deploy the Hubot app on Heroku and I'm getting this build error which seems to be linked to the usage of the backtick "`" symbol in the npm's lib unsupported.js file.
(Line 28 of this file: https://github.com/npm/npm/blob/latest/lib/utils/unsupported.js)

Is there any chance of getting this fixed, or a suggestion of a workaround?

`Natalias-Tardis:myhubot natalia$ git push heroku master`

`Counting objects: 15, done.`

`Delta compression using up to 4 threads.`

`Compressing objects: 100% (11/11), done.`

`Writing objects: 100% (15/15), 17.50 KiB | 0 bytes/s, done.`

`Total 15 (delta 0), reused 0 (delta 0)`

`remote: Compressing source files... done.`

`remote: Building source:`

`remote:`

`remote: -----> Node.js app detected`

`remote:`

`remote: -----> Creating runtime environment`

`remote:`

`remote:        NPM_CONFIG_LOGLEVEL=error`

`remote:        NPM_CONFIG_PRODUCTION=true`

`remote:        NODE_VERBOSE=false`

`remote:        NODE_ENV=production`

`remote:        NODE_MODULES_CACHE=true`

`remote:`

`remote: -----> Installing binaries`

`remote:        engines.node (package.json):  0.10.x`

`remote:        engines.npm (package.json):   unspecified (use default)`

`remote:`

`remote:        Resolving node version 0.10.x...`

`remote:        Downloading and installing node 0.10.48...`

`remote:        Detected package-lock.json: defaulting npm to version 5.x.x`

`remote:        Bootstrapping npm 5.x.x (replacing 2.15.1)...`

`remote:`

`remote: /tmp/build_29ae4dc962b314270f344f772059ec1b/.heroku/node/lib/node_modules/npm/lib/utils/unsupported.js:27`

``remote:         console.error(`a bug known to break npm. Please update to at least ${r``

`remote:                       ^`

`remote: SyntaxError: Unexpected token ILLEGAL`

`remote:     at Module._compile (module.js:439:25)`

`remote:     at Object.Module._extensions..js (module.js:474:10)`

`remote:     at Module.load (module.js:356:32)`

`remote:     at Function.Module._load (module.js:312:12)`

`remote:     at Module.require (module.js:364:17)`

`remote:     at require (module.js:380:17)`

`remote:     at /tmp/build_29ae4dc962b314270f344f772059ec1b/.heroku/node/lib/node_modules/npm/bin/npm-cli.js:19:21`

`remote:     at Object.<anonymous> (/tmp/build_29ae4dc962b314270f344f772059ec1b/.heroku/node/lib/node_modules/npm/bin/npm-cli.js:92:3)`

`remote:     at Module._compile (module.js:456:26)`

`remote:     at Object.Module._extensions..js (module.js:474:10)`

`remote:        npm  installed`

**Comment by michaeloboyle** [comment]
@uCreateStudio since the change needed is to npm, recommend opening an issue in that repo. Looks like the change was made here: https://github.com/npm/npm/commit/2a11f021561acb1eb1ad4ad45ad955793b1eb4af#diff-1240a890730acc445832e67a85023f96
