### ISSUE TITLE
Hubot is hard to merge with Google assitant

### ISSUE THREAD

**Issue by ileathan** [hubotio/hubot#1421]
Let me know the best place to post this comment on the internet and ill move it there 🗡 

But since technically its an issue I have with hubot AND google assistant ill submit feedback to the latter and post the issue here.

I want to say stuff like "Ok google ping" instead of "Hubot ping".

I currently have various devices running both google assistant and hubot and being the hacker i am i created a specific app for a hubot command such that when I say "Ok google launch ping" it runs the script with a fake message object and returns "pong" as expected.

Obviously this is a bad approach since id need to make apps for all my commands, plus the google assistant doesn't respond "pong" I see that on the terminal (from the adapter).

 What would be a more efficient way to do this?

**Comment by ileathan** [comment]
This app http://www.seabreezecomputers.com/speech/#scripting defaults to using the google assistant and completely makes hubot easy to merge with google assitant :D 

I would close this issue now, but stupid google locked my account so i cant actually go test it, and you need to purchase it to default to google assitant + access scripting D:

**Comment by mose** [comment]
Well this is good to know. Let's close this issue, it will still show in search results.

**Comment by skbrown333** [comment]
https://www.npmjs.com/package/hubot-assistant
