### ISSUE TITLE
Need help. Newbie.

### ISSUE THREAD

**Issue by vivekpatani** [hubotio/hubot#1422]
I just used the pug me bot. Is there a way for me to post a message from postman (or any way for me to script the message) to the pug me coffee script which will then trigger a chat message? I'm currently running the pug me script locally and sending a message to the remote server successfully.

Thank you for your help.

**Comment by joh6nn** [comment]
I'm sorry that you didn't get assistance in a timely manner, but since it's been 5 years since your original request, I'm going to close this out
