### ISSUE TITLE
my win7 system hubot setup The following problems occur?

### ISSUE THREAD

**Issue by zhengsh** [hubotio/hubot#1423]
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "hubot" under a package
npm ERR! also called "hubot". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-01-31T15_30_30_010Z-debug.log

**Comment by joh6nn** [comment]
I'm sorry that you didn't get timely assistance with this, but since it's been 5 years, I'm closing it out.
