### ISSUE TITLE
Autocompletion in shell adapter

### ISSUE THREAD

**Issue by strowk** [hubotio/hubot#1431]
I think many users of hubot would like to achieve ability to autocomplete commands in their day to day activities. Not all chats allows to autocomplete for bots, but shell certainly has this ability 
( https://preview.npmjs.com/package/cline ) , which means it could be added as an optional integration feature to adapters API and implemented in Shell adapter so that in future it could be supported by any adapter.

Use case: 
1) Developer introduce respond entry:

``` coffeescript
  robot.respond /run (job|script|car|source_build)/i, (res) ->
      # run something
```

2) User runs bin/hubot --name hubot
3) User types "hu" and press Tab
4) Shell attaches "bot" to line
5) User types space then "r" and then press Tab
6) Shell attaches "un" to line
7) User types space then "sc" and then press Tab
8) Shell attaches "ript" to line
9) User erases "script", types "s" and press Tab
10) Shell prints variants to choose: "script source_build"
11) User prints "o", press Tab
12) Shell attaches "urce_build" to line
13) User erases "source_build" and press Tab
14) Shell prints variants to choose: "job script car source_build"

**Comment by joeyguerra** [comment]
Replaced shell with readline implementation. Let's try that.
