### ISSUE TITLE
message when you do not have an answer

### ISSUE THREAD

**Issue by meirinaldojunior** [hubotio/hubot#1432]
is it possible to set up an auto-reply message if there is no answer to the question?

**Comment by aflansburg** [comment]
There was mention of a catchAll() method in [issue #1394 ](https://github.com/hubotio/hubot/issues/1394), but I have not been able to get it to work on my Heroku-deployed Hubot.

**Comment by meirinaldojunior** [comment]
Ohh yeah!
I will read about.

thanks very much.
