### ISSUE TITLE
Support for Google Hangouts Chat

### ISSUE THREAD

**Issue by tedsc** [hubotio/hubot#1433]
Hi Folks,

Do you have any plans to integrate Hubot with the new Google Hangouts Chat (not Google Hangouts https://hangouts.google.com/ , not Google Chat https://support.google.com/chat/?hl=en, but Google Hangouts Chat - https://gsuite.google.com/products/chat/)

**Comment by mose** [comment]
In my workplace people begin to talk about this new chat. I guess I will need that too. If nobody does it, I will. But timeline is undefined.

**Comment by aairey** [comment]
It shouldn't be too hard.
https://developers.google.com/hangouts/chat/reference/

**Comment by teonivalois** [comment]
I've created the very first version of it, and is working fine. https://github.com/teonivalois/hubot-hangoutschat

**Comment by kahowell** [comment]
FYI, it looks like there's now a more official option: https://developers.google.com/hangouts/chat/how-tos/integrate-hubot

**Comment by aairey** [comment]
Found the code here:
https://github.com/gsuitedevs/hubot-google-hangouts-chat

I guess we can close this, @tedsc ?
