### ISSUE TITLE
Convert documentation to JavaScript (decaffinate)

### ISSUE THREAD

**Issue by rektide** [hubotio/hubot#1436]
The docs should stop being a special ❄️ and switch to the language everyone knows and uses these days, to increase accessibility.

That said, [coffeescript is still remarkably present](http://redmonk.com/sogrady/2018/03/07/language-rankings-1-18/), but I expect a lot of this is legacy.

**Comment by abowail501** [comment]
https://strawpoll.com/pgy9k5xk

Number 4- علي

**Comment by technicalpickles** [comment]
Duplicate of https://github.com/hubotio/hubot/issues/1087
