### ISSUE TITLE
Hubot Enterprise HipChat

### ISSUE THREAD

**Issue by jaydhary14** [hubotio/hubot#1438]
So I need some help to configure Hubot for enterprise hipchat. 

I have installed Hubot locally on OSX and have configured my "actual hipchat user name" as Hubot bot

I have set the properties 
------------------------------
export HUBOT_LOG_LEVEL=info
export HUBOT_HIPCHAT_JOIN_PUBLIC_ROOMS=false
export HUBOT_HIPCHAT_JOIN_ROOMS_ON_INVITE=true
export HUBOT_HIPCHAT_JID=*******@chat.hipchat.com
export HUBOT_HIPCHAT_ROOMS=*******@conf.hipchat.com
export HUBOT_HIPCHAT_PASSWORD=********
export HUBOT_HIPCHAT_HOST=chat.hipchat.com
export HUBOT_HIPCHAT_XMPP_DOMAIN=btf.hipchat.com
--------------------------------

In Log I can see the rooms I am been invited to (Which is good)

[Fri Mar 23 2018 16:10:04 GMT-0400 (EDT)] INFO Got invite to ****@conf.hipchat.com from ******@chat.hipchat.com 
[Fri Mar 23 2018 16:10:03 GMT-0400 (EDT)] INFO Got invite to ******@conf.hipchat.com from ******@chat.hipchat.com
[Fri Mar 23 2018 16:10:03 GMT-0400 (EDT)] INFO Got invite to ******@conf.hipchat.com from ******@chat.hipchat.com 
[Fri Mar 23 2018 16:10:03 GMT-0400 (EDT)] INFO Got invite to ******@conf.hipchat.com from ******@chat.hipchat.com
[Fri Mar 23 2018 16:10:04 GMT-0400 (EDT)] INFO Got invite to ******@conf.hipchat.com from ******@chat.hipchat.com 

But in Log I see this as well (Not sure if that's a good thing or bad thing)

[Fri Mar 23 2018 16:21:06 GMT-0400 (EDT)] DEBUG No listeners executed; falling back to catch-all
[Fri Mar 23 2018 16:21:06 GMT-0400 (EDT)] DEBUG No listeners executed; falling back to catch-all

Main Issue : I am not getting response from Hubot in HipChat

for example - in HipChat
Where Bot is my actual HipChat User Name

HipChat - @Bot help (No Response from bot)
Hubot Log - [Fri Mar 23 2018 16:21:35 GMT-0400 (EDT)] DEBUG  OUT > <r/> 

HipChat - @Bot Ping (No Response from bot)
Hubot Log - [Fri Mar 23 2018 16:29:35 GMT-0400 (EDT)] DEBUG  OUT > <r/>

**Comment by joh6nn** [comment]
@joeyguerra HipChat is [completely dead](https://en.wikipedia.org/wiki/HipChat) as of 2019, I think we can consider this closed
