### ISSUE TITLE
FIx and improve documentation for new adapters

### ISSUE THREAD

**Issue by teonivalois** [hubotio/hubot#1439]
I've tried to create an adapter. for myself, but after following all steps from https://hubot.github.com/docs/adapters/development/ all I get is _ERROR Cannot load adapter sample - Error: Cannot find module 'hubot-sample'_

Please update the documentation.

**Comment by loveonelong** [comment]
You can see this about your problem.
Duplicate of #804 
I think the document is really too old too.

**Comment by joeyguerra** [comment]
[Development](https://github.com/hubotio/hubot/blob/master/docs/adapters/development.md) has been updated for Javascript.
