### ISSUE TITLE
How to make a http request use robot.http?

### ISSUE THREAD

**Issue by bestony** [hubotio/hubot#1441]
I write hubot script in javascript ,

and here is not a document for javascript ,only coffeescript. 

coffeescript is here: https://hubot.github.com/docs/scripting/

## WHAT I WANT 

A example for javascript version of robot.http().post

**Comment by KeesCBakker** [comment]
I currently use the Axios npm package to do the requests, but I have been wrapping the Hubot HTTP client into an ES6 prommise: https://keestalkstech.com/2018/01/hubot-es6-promises/

Here's an example for a GET:
```
const norrisUrl = 'https://api.icndb.com/jokes/random';

// wrap with promise
new Promise((resolve, reject) => 
    robot.http(norrisUrl).get()((err, response, body) =>
        err ? reject(err) : resolve(body)
    )
)

// parse to js object
.then(body => JSON.parse(body))
```
