### ISSUE TITLE
Adding/removing a listener while handling a message causes unexpected behaviour

### ISSUE THREAD

**Issue by Place1** [hubotio/hubot#1445]
Mutating the list of listeners for the robot by using functions like `.hear` or `.respond`, or just mutating the `robot.listeners` array while handling a message leads to unexpected behaviour.

For example:
1. if you add a new listener while handling a message, the new listener will also receive the message being handled. This is somewhat unexpected, at least to me, as my intuition told me that the new listener would only start receiving subsequent messages.

2. if you add a new listener by inserting it into the start of the listeners array then it won't receive the currently being handled message, but instead the current listener will receive the same message again

etc.

here's an example of what i mean by "mutating the list of listeners while handling a message"
```
module.exports = function(bot) {
  bot.respond(/echo/, ((response) => {
    response.reply("ok i'll listen for you");
    bot.hear(/.*/, { id: 'myid' }, (response) => {
      response.reply(reponse.message.text);
      const listenerIndex = bot.listeners.findIndex((listener) => listener.options.id === 'myid');
      if (listenerIndex !== -1) {
        bot.listeners.splice(listenerIndex, 1);
      }
    });
  }));
}
```

In the example the top level `bot.respond`'s callback mutates the listener array by calling `bot.hear` and then splicing to remove a listener later on.

I believe this happens because of the following line:
https://github.com/hubotio/hubot/blob/d0c13d2d8cd1ba30dc7f8765778988ca5a4d00c9/src/robot.js#L310

I believe this should pass a copy of the listeners array so that any modifications to that array within a handler doesn't cause side effects in the overall processing for a given message.

This bug happens because of how async.js's 'detectSeries' is implemented:

```
// detectSeries actually does the iteration in async.eachSeries
async.eachSeries = function (arr, iterator, callback) {
        callback = callback || function () {};
        if (!arr.length) {
            return callback();
        }
        var completed = 0;
        var iterate = function () {
            iterator(arr[completed], function (err) {
                if (err) {
                    callback(err);
                    callback = function () {};
                }
                else {
                    completed += 1;
                    if (completed >= arr.length) {
                        callback();
                    }
                    else {
                        iterate();
                    }
                }
            });
        };
        iterate();
    };
```

**Comment by joeyguerra** [comment]
replaced async module with async/await code.
