### ISSUE TITLE
Which port actually Hubot points if the 8080 is pre-occupied

### ISSUE THREAD

**Issue by prashanth-sams** [hubotio/hubot#1450]
I am using the `localhost:8080` for jenkins... and not sure how to get the host url for hubot, like where it runs

How to change the port number?

**Comment by prashanth-sams** [comment]
Adjusting from `node_modules > hubot > src > robot.coffee` did help

![port](https://user-images.githubusercontent.com/2948696/42818855-ffd0d288-89e2-11e8-9b74-a52393316633.png)

**Comment by 2ZZ** [comment]
you can also set EXPRESS_PORT env variable
`export EXPRESS_PORT=8081`
