### ISSUE TITLE
Android support for Hubot

### ISSUE THREAD

**Issue by pronoym99** [hubotio/hubot#1463]
please add mobile os support for hubot for ready development in the mobile app domain

**Comment by stephenyeargin** [comment]
Hubot is designed to connect to various platforms (Slack, IRC, Campfire, etc.) that already have mobile applications. The bot instance itself does not run on mobile platforms such as iOS or Android. If you want to have Hubot available on mobile, it would first need to connect [through one of its adapters](https://hubot.github.com/docs/adapters/) to a service that has an application for your device.

I'm not sure this feature request is something that would be considered given what the project does today.

**Comment by pronoym99** [comment]
So are there any Hubot developers who are working on OR have thought of working on the mobile adaptability of this project?
