### ISSUE TITLE
Slack invite app is down on heroku

### ISSUE THREAD

**Issue by JCMais** [hubotio/hubot#1478]
https://hubot-slackin.herokuapp.com/ shows:

![image](https://user-images.githubusercontent.com/1041647/48445884-e34a6800-e77e-11e8-8f6a-b2b092ecc342.png)

**Comment by joeyguerra** [comment]
Are we done? No more Hubot? Or just busy?

**Comment by toshitapandey** [comment]
I am also facing this issue. Is it being resolved by anyone?

**Comment by joeyguerra** [comment]
I haven't seen any response from the maintainers. What do we do when there doesn't appear to be any more activity on this repo?

**Comment by metabsd** [comment]
I have the same problem.

**Comment by joeyguerra** [comment]
Just found a hubot channel in Gitter: https://app.gitter.im/#/room/#github_hubot:gitter.im
