### ISSUE TITLE
Hubot help system improvements

### ISSUE THREAD

**Issue by arigoldx** [hubotio/hubot#1490]
Hello there,

I've searched far and wide and even [commented](https://github.com/hubotio/hubot/issues/396#issuecomment-455020900) on an old hopefully-related issue but no 🎲 🎲.

Basically I feel like hubot's help system could be waaaaaaaay better. More specifically, it could be better than an [alphabetically sorted](https://github.com/hubotio/hubot/blob/3e32c1e380ca9ce39a7c25a4d277c24de6c70c7a/src/robot.js#L515) parsing of [comments that are "documentation sections"](https://github.com/hubotio/hubot/blob/3e32c1e380ca9ce39a7c25a4d277c24de6c70c7a/src/robot.js#L544).

I was about to begin working on it when I thought I'd open an issue here -- anyone do anything else?

Or maybe the current help system is enough? That is, maybe I'm doing something wrong?

**Comment by cycomachead** [comment]
#862 and this were one attempt at improving things:
https://github.com/hubotio/hubot/pull/917/files

Unfortunately, I never got around to finishing that up, and it was a little hacky. 
That would enable to add more script/plugin specific context to help queries, which probably belongs in hubot-help.

**Comment by msudol** [comment]
> 
> 
> Hello there,
> 
> I've searched far and wide and even [commented](https://github.com/hubotio/hubot/issues/396#issuecomment-455020900) on an old hopefully-related issue but no 🎲 🎲.
> 
> Basically I feel like hubot's help system could be waaaaaaaay better. More specifically, it could be better than an [alphabetically sorted](https://github.com/hubotio/hubot/blob/3e32c1e380ca9ce39a7c25a4d277c24de6c70c7a/src/robot.js#L515) parsing of [comments that are "documentation sections"](https://github.com/hubotio/hubot/blob/3e32c1e380ca9ce39a7c25a4d277c24de6c70c7a/src/robot.js#L544).
> 
> I was about to begin working on it when I thought I'd open an issue here -- anyone do anything else?
> 
> Or maybe the current help system is enough? That is, maybe I'm doing something wrong?

I Decided to publish a new package to replace hubot-help with a bunch of fixes and feature improvements, if you are still using hubot, give hubot-help-plus a try. https://www.npmjs.com/package/hubot-help-plus

It's still the old system but, at least it works
