### ISSUE TITLE
HTTP daemon cannot be disabled

### ISSUE THREAD

**Issue by hatxet** [hubotio/hubot#1491]
According to `src/robot.js` [on line 26](https://github.com/hubotio/hubot/blob/067a70d930dc186c4c1412503c701df3cad5af5f/src/robot.js#L26), it's possible to disable the HTTP daemon by setting `httpd` to false.

Even though it sets up a null router, HTTP requests are still executed because it always returns a scoped-http-client object.
https://github.com/hubotio/hubot/blob/067a70d930dc186c4c1412503c701df3cad5af5f/src/robot.js#L709

In my case it means that tests made with `hubot-test-helper` won't work as expected when the rooms have `httpd` disabled.

I think an easy solution would be to replace `get` and `post` from the http client object with empty functions if `httpd` is set to false.

**Comment by technicalpickles** [comment]
This was fixed when https://github.com/hubotio/hubot/pull/1581 landed, which includes https://github.com/hubotio/hubot/pull/1548
