### ISSUE TITLE
Massive logger messages

### ISSUE THREAD

**Issue by terorie** [hubotio/hubot#1492]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/21371810/52141181-2c5ed980-2655-11e9-86a6-bfcb5668a449.png">

`[Fri Feb 01 2019 19:09:59 GMT+0100 (Central European Standard Time)]` is really hard to read as a prefix.

How about `[2019-02-01 19:09:59 GMT+1]`?

**Comment by joeyguerra** [comment]
I think `new Date` is hard coded so you'd have to change the `Log` module.
```log: function(levelStr, args) {
    if (exports[levelStr] <= this.level) {
      var msg = fmt.apply(null, args);
      this.stream.write(
          '[' + new Date + ']'
        + ' ' + levelStr
        + ' ' + msg
        + '\n'
      );
    }
  },```
