### ISSUE TITLE
Dead link to slack in README.md

### ISSUE THREAD

**Issue by jjshoe** [hubotio/hubot#1493]
Line https://github.com/hubotio/hubot/blame/master/README.md#L16

This link no longer works

**Comment by jjshoe** [comment]
@bkeepers - You seem like the best person to ping about the broken slack link in the readme

**Comment by halkeye** [comment]
@technicalpickles @mistydemeo

**Comment by halkeye** [comment]
According to the roadmap (https://github.com/hubotio/hubot/pull/1323), @technicalpickles @bkeepers @mose and @gr2m are the official peeoples

So pinging all of them.

Sorry for the double pings sometimes people.

**Comment by jmeeter** [comment]
So is this project officially dead? No updates for almost a year, Slack is unresponsive... RIP.

**Comment by rajasibero** [comment]
> Line https://github.com/hubotio/hubot/blame/master/README.md#L16
> 
> This link no longer works

**Comment by technicalpickles** [comment]
The link has since been removed. I'm not sure the status of it, since my account is uses my old work email, and can't invite ourselves another way 🙃
