### ISSUE TITLE
How to implement sync http in .coffee file

### ISSUE THREAD

**Issue by Dr-kyle** [hubotio/hubot#1503]
I want to wait http response, such as:
getRequest = () -> 
  robot.http(url).get() (err, response, body) ->
  return body

response = getRequest()
// dosomething

Can you give me a example, Thanks!!

**Comment by joeyguerra** [comment]
Just taking a stab here...

```coffee
response = getRequest = () ->
robot.http(url).get() (err, res, body) ->
return res
```

**Comment by halkeye** [comment]
You can't really do it sync, cause its a sync operation. 
In es6 (like non coffescript) you can use promises and await async

```
function httpGetPromise(url) {
  return new Promise(function(resolve, reject) {
    robot.http(url).get(function(err, response, body) {
      if (err) { return reject(err); }
      resolve({ response: response, body: body })
    })
  })
}

const { response } = await httpGetPromise('http://url');
```
