### ISSUE TITLE
HUBOT_BASE_URL

### ISSUE THREAD

**Issue by meaz** [hubotio/hubot#1510]
I have a xmpp server on which I started a hubot.
For one of the scripts I wanted to use (factoids), I'm being asked to set this 
`HUBOT_BASE_URL`

How do I set/know that?

**Comment by joeyguerra** [comment]
You can just set it as an environment variable when you start Hubot. In MacOS it would be like `HUBOT_BASE_URL=https://www.yourehuboturl.com hubot`. The next question is what should your HUBOT_BASEURL be in the first place? I don't even see that environment variable in the codebase so I'm unsure why you're seeing that.

**Comment by meaz** [comment]
there: [https://github.com/therealklanni/hubot-factoids/blob/master/src/factoids.coffee](https://github.com/therealklanni/hubot-factoids/blob/master/src/factoids.coffee)

> The next question is what should your HUBOT_BASEURL be in the first place?
yep. That is my question! What should it be for a xmpp server?

**Comment by joeyguerra** [comment]
Does that mean this issue should be closed?
