### ISSUE TITLE
How to remove/disable hubot-shipit

### ISSUE THREAD

**Issue by stpaultim** [hubotio/hubot#1517]
I can't reopen this ticket: https://github.com/hubotio/hubot/issues/1397 so, here is a new one.

I've removed hubot-shipit from external-scripts.json
I've run `npm uninstall hubot-shipit` and made sure that `hubot-shipit` is no longer listed in either the `package.json` or `package-lock.json` file. But, when I run Hubot, I get the following error

`ERROR Error loading scripts from npm package - Error: Cannot find module 'hubot-shipit'`

Any ideas on why Hubot is still looking for `hubot-shipit` and/or how I can disable this module?

I've searched the code base for "shipit" and nothing is turning up, so I'm not sure why npm is looking for the hubot-shipit module.

**Comment by EddyLuten** [comment]
You must also remove the module name from the `external-scripts.json` file in the project root directory otherwise Hubot will try to activate this module when it initializes.

**Comment by joeyguerra** [comment]
Gone stale.
