### ISSUE TITLE
Activate hubot!

### ISSUE THREAD

**Issue by owaranaidobby** [hubotio/hubot#1521]
Currently, hubot has some issues and some pull requests, but there is the problem what authorized people are not working. For it, I want hubot owner to allow me or someone who can activate hubot to be contributors.

However, the hubotio to which hubot belongs seems to have only one people( @mose  ). I would like to ask @mose  if possible.

**Comment by kevinsearle** [comment]
Might be time to fork.

**Comment by owaranaidobby** [comment]
Thanks for reacting. And sorry for the late reply.

mmm...ok.
I hope that there is progress in the official development, but there is no help for it.

Thanks!
