### ISSUE TITLE
Not notification for failing CI after pushing a commit to a deployed branch

### ISSUE THREAD

**Issue by hfaulds** [hubotio/hubot#1524]
Quite often we deploy launch to lab and notice a change is required. Pushing a change automatically deploys, unless CI fails and then it silently errors.

**Comment by joh6nn** [comment]
@hfaulds I can't tell what this is in reference to, but I get the impression that it was maybe filed against the wrong project by accident. Can you either confirm that this is an issue with hubot and provide more detail, or can you confirm that this was filed here in error and close it out?

Thanks :)

**Comment by hfaulds** [comment]
@joh6nn yeah, I guess this is a heaven issue actually (if I queued a lab deploy of a moda app, subsequent commits pushed would cause it to deploy those commits, but if anything failed it failed silently).

That said I haven't used heaven in over a year and I don't think this is a big deal so am just going to close.
