### ISSUE TITLE
User authenticity check

### ISSUE THREAD

**Issue by Luxorvs** [hubotio/hubot#1532]
Good afternoon. I use the Rocketchat server. I need to create a bot. I am new to this topic. We need a bot that will authenticate the user during correspondence through a personal dialogue. The script should check the user with the database automatically, and display the necessary information for the requested command.
An example of dialogue. What it should look like!
- **IvanovMM**: vacation
- **bot**: your vacation "date from base"
- **IvanovMM**: phone
- **bot**: your telephone is “telephone from base”

I have a bot where he perceives commands, reacts to them. And also the part where the export is from the base. But I can not implement authentication. At the moment, everyone can find out information on each. But it is necessary that the bot checks who writes and provides information only for this user. Who can advise what?

================================================================
Добрый день. Я пользуюсь сервером Rocketchat. Мне необходимо создать бота. Я в этой теме новичок. Нужен бот, который будет проводить проверку подлинности пользователя, при переписке через личный диалог.  Скрипт должен проверять пользователя с базой данных автоматически, и выводил необходимую информацию по запрашиваемой команде.
Пример диалога.  Как это должно выглядеть! 
- **IvanovMM**:  отпуск
- **bot**: ваш отпуск «дата из базы»
- **IvanovMM**: телефон
- **bot**: ваш телефон «телефон из базы»

У меня есть бот, где он воспринимает команды, реагирует на них. А так же часть, где делает экспорт из базы. Но проверку подлинности реализовать не могу. На данный момент, каждый может узнать информацию по каждому. А надо что бы бот, сверял кто пишет и выдавал информацию только по этому пользователю. Кто что может посоветовать?

**Comment by Trinadad** [comment]
> Good afternoon. I use the Rocketchat server. I need to create a bot. I am new to this topic. We need a bot that will authenticate the user during correspondence through a personal dialogue. The script should check the user with the database automatically, and display the necessary information for the requested command.
> An example of dialogue. What it should look like!
> 
> * **IvanovMM**: vacation
> * **bot**: your vacation "date from base"
> * **IvanovMM**: phone
> * **bot**: your telephone is “telephone from base”
> 
> I have a bot where he perceives commands, reacts to them. And also the part where the export is from the base. But I can not implement authentication. At the moment, everyone can find out information on each. But it is necessary that the bot checks who writes and provides information only for this user. Who can advise what?
> 
> ================================================================
> Добрый день. Я пользуюсь сервером Rocketchat. Мне необходимо создать бота. Я в этой теме новичок. Нужен бот, который будет проводить проверку подлинности пользователя, при переписке через личный диалог. Скрипт должен проверять пользователя с базой данных автоматически, и выводил необходимую информацию по запрашиваемой команде.
> Пример диалога. Как это должно выглядеть!
> 
> * **IvanovMM**:  отпуск
> * **bot**: ваш отпуск «дата из базы»
> * **IvanovMM**: телефон
> * **bot**: ваш телефон «телефон из базы»
> 
> У меня есть бот, где он воспринимает команды, реагирует на них. А так же часть, где делает экспорт из базы. Но проверку подлинности реализовать не могу. На данный момент, каждый может узнать информацию по каждому. А надо что бы бот, сверял кто пишет и выдавал информацию только по этому пользователю. Кто что может посоветовать?

#742 is this correct

**Comment by joeyguerra** [comment]
Checkout [Restricting Access to Commands](https://github.com/hubotio/hubot/blob/master/docs/patterns.md#restricting-access-to-commands)
