### ISSUE TITLE
Hubot-slack responding same message twice

### ISSUE THREAD

**Issue by aindurthi** [hubotio/hubot#1538]
Recently, I am trying to connect my bot which is developed using hubot framework with slack channels. I am trying to deploy it in ECS docker container.For first time deployment, the bot is working fine. For example, if I give the respective message to it is only responding with the expected message once. But after doing some code modifications and tried to redeploy into ECS container, it is responding with the same message twice. Can someone please help me on this.

**Comment by joeyguerra** [comment]
I suspect there's 2 instances of Hubot running.
