### ISSUE TITLE
ERROR ReplyError: Ready check failed: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by fengweiyuan** [hubotio/hubot#1540]
[Thu Sep 03 2020 20:12:26 GMT+0800 (中国标准时间)] ERROR hubot-heroku-keepalive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s | grep web.url | cut -d= -f2)`
[Thu Sep 03 2020 20:12:26 GMT+0800 (中国标准时间)] ERROR ReplyError: Ready check failed: NOAUTH Authentication required.
  at parseError (/Users/fwy/data/hubot/node_modules/redis-parser/lib/parser.js:193:12)
  at parseType (/Users/fwy/data/hubot/node_modules/redis-parser/lib/parser.js:303:14)

why?

**Comment by joeyguerra** [comment]
Gone stale.
