### ISSUE TITLE
On heroku cedar stack -> bin/hubot: 3: npm: not found

### ISSUE THREAD

**Issue by vlpeng** [hubotio/hubot#155]
I followed up https://github.com/github/hubot/wiki/Hubot-on-Heroku and deploy `hubot-1.1.9.tar.gz` to heroku. However I always encountered this issue:
- 2011-11-07T18:20:14+00:00 heroku[app.1]: Starting process with command `bin/hubot -a campfire -n Hubot`
- 2011-11-07T18:20:14+00:00 app[app.1]: bin/hubot: 3: npm: not found
### gist

Here the details of heroku logs, https://gist.github.com/1345730
### help me...

I am wondering I miss something in heroku deployment of procedure, since I check this http://devcenter.heroku.com/articles/node-js for many times.
### hubot image me @ local is working

Please refer https://gist.github.com/1345763

**Comment by joanrodriguez** [comment]
I had the same problem which I solved by erasing the node_modules folder and then reinstalling every module with `npm install --save`
Yo had installed every modules but nothing in package.json, and the gitignore was ignoring node_modules
