### ISSUE TITLE
가상현실 또는 증강현실 개발

### ISSUE THREAD

**Issue by NakamotoSatoshi10** [hubotio/hubot#1558]
가상현실과 증강현실을 만듦에 있어서는 가장 중요한 점은 현실과 가상현실을 구별하지 못해야 한다는 것 이다.

가상현실에서 쓰는 화폐는 될수있는한 비트코인 또는 알트코인들로 시작을 해야한다.

**Comment by NakamotoSatoshi10** [comment]
> 현실적이지 못하다는 점에서는 확실하지 않습니다.
> 지금 현실은 가상현실일까 진짜 현실일까? 나는 진짜 현실이라고 생각하고있다. 여기 있는 모두도 마찬가지일것이다. 그럼에도 가상현실을 개발하면서 계발 해야 하는 이유는 무엇일까? 앞으로의 미래는 어떻게 될지 아무도 모르기 때문이다. 현재의 올림픽에서 누가 동메달을 목에걸지, 금메달을 은메달을 목에 걸지 모르는것처럼, 이해가 가는가?
> 가까움에서 땔감 코인을 얻을 수 있습니다.
땔감 코인은 무엇인지 모르겠다. Doge coin and bitcoin, bittorrent등 의 코인이 가상현실에서 쓰일수있게끔 만들어야한다.

**Comment by NakamotoSatoshi10** [comment]
당신들의 의견이 궁금하다. 현재 당신들은 어디까지 가능한가? 무엇을 일궈 낼수 있는가? 또한 무엇을 만들수있으며, 아이언맨의 아크원자로를 만들수있는가? 또는 github.com의 홈페이지를 만드는 수준에서 멈춰있는가?

**Comment by NakamotoSatoshi10** [comment]
리미트리스 영화의 뇌를 99%까지 쓸수있는 신약이 있다면, 그 약을 먹을것인가? 부작용이 있다면, 당신은 어떤 부작용까지 감당 가능하겠는가?

**Comment by NakamotoSatoshi10** [comment]
당신의 능력이 궁금하다. 당신은 에디슨인가? 아인슈타인인가? 노벨상을 받아본적이 있는가? 해커인가? 당신은 누구입니까?

**Comment by joeyguerra** [comment]
Spam.
