### ISSUE TITLE
RFC: Alexa adapter?

### ISSUE THREAD

**Issue by pataquets** [hubotio/hubot#1563]
As I'm starting to look for toolkits and SDKs for Alexa development, I wonder if Hubot could be used as a viable framework for creating Alexa Skills. On a cursory read of both the Hubot and Alexa SDK docs, my guess is that it could be, but I'm not deep into neither of them.
However, the question has sparked my curiosity and I'm sharing it, in case someone finds the topic interesting or has ideas or experience about it.

**Comment by joeyguerra** [comment]
I agree. It could theoretically.
