### ISSUE TITLE
I would love to be a maintainer

### ISSUE THREAD

**Issue by joeyguerra** [hubotio/hubot#1566]
It's been years since the master branch has been updated. I'd love to be a maintainer. Is there someone I can speak to about becoming a maintainer of the project?

**Comment by Melekelmot** [comment]
I f you have a few minutes. I think you may be interested

**Comment by joeyguerra** [comment]
@xurizaemon I gave up, forked it (https://github.com/joeyguerra/hubot) and moved on with my own ideas about how to modernize the codebase. I didn't see any momentum in the discussions for one path or another.

That said, I want to help keep Hubot alive. Just don't know what to do to coral the community into a vision and direction, into action.
