### ISSUE TITLE
Adding new maintainers

### ISSUE THREAD

**Issue by technicalpickles** [hubotio/hubot#1588]
As described in https://github.com/hubotio/hubot/issues/1541#issuecomment-1512130320 , I want to add these folks to the Maintainers team:

- @joeyguerra 
- @xurizaemon
- @joh6nn

I've tried to do it manually, but they keep getting removed. I suspect it has to do with [entitlements](https://github.blog/2022-06-09-introducing-entitlements-githubs-open-source-identity-and-access-management-solution/) that are resetting the team?

**Comment by technicalpickles** [comment]
cc @levenleven as someone still on a team at GitHub that may have something to do with hubot?

**Comment by technicalpickles** [comment]
I've tried adding them to hubotio/hubot, so we'll see if that gets wiped as well or not

**Comment by joh6nn** [comment]
I think adding me to hubotio/hubot worked, at least. I've successfully closed several stale issues. Probably best to wait a day before we call that certain, though

**Comment by joeyguerra** [comment]
I just got an invite to the Hubotio org from @entitlements . Thanks ya'll.

**Comment by joeyguerra** [comment]
@technicalpickles can I please get added to the Maintainers team? Or get member access to all the repos in the Hubotio org? I'd like to start updating those other repos as well. Starting with the `Hubot-help` one.

**Comment by technicalpickles** [comment]
I forgot to update here, but I got word that y'all were added to the organization. Organization membership is what it was managing, not teams, so I've updated those manually.
