### ISSUE TITLE
Can I be an owner on the Hubotio org? So that I can also set CI/CD env. variables?

### ISSUE THREAD

**Issue by joeyguerra** [hubotio/hubot#1623]
I'm not an owner of the Hubotio org, so I can't set the NPM_TOKEN or any CI/CD env variables. Since we're the only ones responding to issues, I can help more if I was an owner.

**Comment by joeyguerra** [comment]
@technicalpickles what are you thoughts on making me an owner for the Hubotio org?

**Comment by xurizaemon** [comment]
👋🏼  also here - I think it will be helpful to debug those things if we can have access to manage settings.

**Comment by joeyguerra** [comment]
Yeah. That's exactly what I was thinking. The build was failing for Node.js 14.x and when I removed that version from the strategy matrix, the PR was unmergable because the "check" was still required. I don't know why. But I was unable to check settings and troubleshoot. I was lucky to stumble upon a procedure to get the build to work with 14.x.

Alas, luck (hope) is not a strategy. And since we're now the only ones actively supporting development, it would make sense that we have the permissions to troubleshoot everything.

**Comment by joh6nn** [comment]
I agree it makes sense for you both to be owners now. I probably don't need it at this point in time since I'm way less hands-on at the moment than either of you (which has been impressive and fun to watch!), and if that changes in the future, with you both as owners it's something that's easily fixedu

**Comment by technicalpickles** [comment]
Sorry it took me a bit to get to this. I've changed @xurizaemon and @joeyguerra's role to "Owner". Can y'all verify you can access make changes to those secrets?

**Comment by joeyguerra** [comment]
@technicalpickles I'm still just a member of the org. I can't see any of the advanced settings.

Just a point of clarification. I need to be an owner of the Hubotio org if I'm going to be able to maintain the repos.

**Comment by technicalpickles** [comment]
I suspect that entitlements are managing owners as well. I can work on getting that through with someone at GitHub, but you know how long it took last time. This may be a little harder of a sell, but not positive.

In the mean time, are there any ways to work around that? Like, if it is a matter of environment variables, it will be tedious, but can update each repo that needs them.

We could also try setting sync time to pair on it. I can't really commit to being super responsive (as you can probably figure from observations).

**Comment by joeyguerra** [comment]
It's more about getting the PRs reviewed and approved so I can merge them. I'd also like to define a roadmap and keep updating the codebase to use ES6 import, .mjs file extensions, async/await message sending, and convert the tests to use Node.js Test Runner in order to reduce dependencies. I know you're pretty busy and no one else is responding so I figured if I was an owner, I could run with modernizing the codebase and coming up with a roadmap to evolve Hubot.

Pair programming would be awesome. I'll follow your lead on that since I think you're more time constrained than I am. I'm in the US Central time zone.

**Comment by joeyguerra** [comment]
Thanks @technicalpickles . I was able to merge the hubot-rules PR.

**Comment by xurizaemon** [comment]
I think we can close this now.
