### ISSUE TITLE
Update the license

### ISSUE THREAD

**Issue by lquenti** [hubotio/hubot#1648]
Normally I wouldn't be this pedantic, [but you use this license as the prime example for licensing](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#determining-the-location-of-your-license) so I think it would make sense

**Comment by joh6nn** [comment]
Hrmm. That presents an interesting conundrum:

- Github has largely abdicated the maintenance of this project, so updating the years to read "2011-2023" wouldn't reflect the current reality
- Current practice from large projects suggests [not including years at all](https://hynek.me/til/copyright-years/), but:
- Wholesale removing the years reads largely the same as just updating them to "2011-2023" and implies that Github is still maintaining the project, which again, it's not
- Completely removing the Github attribution feels both sketchy and Wrong:tm:

Anyone have thoughts?

**Comment by xurizaemon** [comment]
We can just leave that file, and it feels apt that it stops at 2017. If anyone representing GitHub wanted to update it I'd be fine with that.

The docs can be improved, eg we could document as

> - add a license file
> - your code hosting platform probably has a button for this
> - or you can obtain open source licenses from https://opensource.org/licenses/
> - this project and many Hubot plugins are MIT licensed (but yours doesn't have to follow suit

BTW thanks for this, which led me to the history entry at b253e94 when I reviewed the history on the license file

**Comment by lquenti** [comment]
(Also, I wanted to say sorry, I just knew hubot by name and didn't know about the abandonment. Really didn't want to be a dick, my bad.)

**Comment by xurizaemon** [comment]
Hey it's fine - we now have a team of maintainers active on the project, GitHub staff's engagement dropped off a few years ago, and now some community users have picked things up.

No hard feelings and no offense taken 😄

**Comment by joeyguerra** [comment]
Is the consensus to leave the copyright years as they are?

**Comment by joh6nn** [comment]
If no one else is worried about it, I think leaving the file as is works for right now. We can always fix it later if it turns into a problem :)

I don't think there's any further action we can take, though. The link @lquenti followed to get here is on Github's official docs, which are outside our control :shrug: I'll go ahead and close this based on that, but if anyone sees an action we can take here, don't hesitate to reopen it.
