### ISSUE TITLE
Run hubot on windows

### ISSUE THREAD

**Issue by lukesmith** [hubotio/hubot#166]
Is this something that would be useful to people?

I'd like to give it a go next week if noone is already working on it.

**Comment by fotijr** [comment]
This is an old thread, but if you're seeing the `'coffee' is not recognized` error, try installing coffee globally.

`npm install -g coffee-script`

You don't need to manually compile to JavaScript, and you shouldn't be going to the hubot folder in node_modules to run hubot.
