### ISSUE TITLE
Upgrade from 7 to 9 causes: "Incorrect number of arguments for middleware callback (expected 1, got 3)"

### ISSUE THREAD

**Issue by KeesCBakker** [hubotio/hubot#1671]
The code I'm using from the bot is:

```js

 robot.receiveMiddleware((context, next, done) => {
        var text = context.response.message.text;
        var newText = mapping.process(text);
        if (text != newText) {
            context.response.message.text = newText;
            if (robot.logger) {
                robot.logger.info(`Routing '${text}' to '${newText}'.`);
            }
        }
        next(done);
    });

```

**Comment by joeyguerra** [comment]
Yes, there was an API change between 7 and v9. Specifically, the move to async/await style code. The code above would look like the following for v9:

```js
 robot.receiveMiddleware(async context => {
        var text = context.response.message.text;
        var newText = mapping.process(text);
        if (text != newText) {
            context.response.message.text = newText;
            if (robot.logger) {
                robot.logger.info(`Routing '${text}' to '${newText}'.`);
            }
        }
        return true;
    });
```

Returning `true` will tell the code to continue the pipeline. Returning `false` will halt the pipeline. Looking at [robot.receive](https://github.com/hubotio/hubot/blob/a4219a0e179a7766dce4fd92bd384c145deff8de/src/robot.js#L278), you'll see the infrastructure that does this.

**Comment by KeesCBakker** [comment]
Awesome! Let me upgrade some code. Looks like we also need to update  `hubot-mock-adapter`.

![image](https://github.com/hubotio/hubot/assets/583193/4ac8e687-f7cd-43ee-bfb5-bc23146ef519)

**Comment by KeesCBakker** [comment]
Fortunately the upgrade was not very hard: https://github.com/KeesCBakker/hubot-command-mapper/commit/2504fd5fa1fbe5c27b04044e0fdceb1a514e8e51

**Comment by joeyguerra** [comment]
@KeesCBakker I'm really glad to hear that. I've been making some big moves in the codebase with very little feedback to guide decisions.

What are your thoughts about closing this issue?

**Comment by KeesCBakker** [comment]
Yeah, we can close it. Should I open a new ticket for the mock adapter peer dependency?

**Comment by joeyguerra** [comment]
@KeesCBakker  yes please. That way it stands out as I continue to monitor issues from the main repo page.
