### ISSUE TITLE
response.reply is not a function in CatchAll listener

### ISSUE THREAD

**Issue by joeyguerra** [hubotio/hubot#1721]
Someone submitted PR #1718. After no response about a test, I wrote a failing test to highlight the scenario.

**Comment by PColuccio** [comment]
@joeyguerra Thanks for getting the fix in! I was hoping to get a test written this weekend.

**Comment by joeyguerra** [comment]
You're welcome. A test would still be great. The more perspectives I can get on this, the better.

**Comment by joeyguerra** [comment]
By the way, I believe this https://github.com/hubotio/hubot/blob/f212f5d31011dbec938d1419bf4a84cf61571128/src/Robot.mjs#L321 is the start of the call stack that results in calling catch all listeners.
