### ISSUE TITLE
`Brain.users()` claims it returns an Array but returns an Object

### ISSUE THREAD

**Issue by yincrash** [hubotio/hubot#1724]
https://github.com/hubotio/hubot/blob/f212f5d31011dbec938d1419bf4a84cf61571128/src/Brain.mjs#L160

When attempting to use `.forEach` on the return result, it causes an error since it's not an `Array`. A fix could either be extracting all the Users into an Array to return or change the promise of what the function should return.

**Comment by joeyguerra** [comment]
I'll update the comment.
