### ISSUE TITLE
Can not fetch HTTP request @Heroku

### ISSUE THREAD

**Issue by alxgsv** [hubotio/hubot#233]
Can someone help me on this topic? I set up Hubot on Heroku, wrote script to fetch HTTP. But in log on Heroku i see this:

```
Error H14 (No web processes running) -> GET testbot1365.herokuapp.com/notifications dyno= queue= wait= service= status=503 bytes
```

Maybe heroku does not support this?

**Comment by dylanh724** [comment]
So...................... still an issue years later, for me. No resolution?
