### ISSUE TITLE
Adopt botriot style description and help

### ISSUE THREAD

**Issue by atmos** [hubotio/hubot#249]
@jonrohan showed me this earlier today and I'd love for our scripts to support something like these.

``` js
exports.wiki = {
  description: 'Searches Wikipedia.org for the given input and returns a link to the most relevant article.',
  func: function (room, msg, options) {
    if (!msg) {
      return room.error(new UserError("You must provide some input. I can't read your mind."))
    }

    var uri = 'http://en.wikipedia.org/w/api.php?action=opensearch&search=' + encodeURIComponent(msg) + '&format=json'
    jsonHelper(room, uri, function(body) {
      if (body[1].length > 0) {
        var key = body[1][0]
        room.speak("http://en.wikipedia.org/wiki/"+encodeURIComponent(key))
      } else {
        room.speak("No wikipedia article found")
      }
    })
  }
}
```
- First the description is tied to the trigger response, this will inevitably be a pain in the ass to upgrade to.
- some commands are using commander, an optparse like library to make commands more unix like, kinda cool.

Any thoughts on doing something like this for hubot 3 @tombell ?

**Comment by ileathan** [comment]
@sirkitree you would edit the ./node_modules/hubot-help/ scripts. I personally just have the bot spit out a the link and then people can browse all the commands in the browser. It really depends you can make your own `robot.respond /help (\S+)/, (msg) ->` . 

I like this script pattern alot more than another one i looked at but i sure hope this doesnt add more complexity when i code I havnt done more than just look at it and its atleast very readable unlike the other one ive seen.
