### ISSUE TITLE
Help categories

### ISSUE THREAD

**Issue by Iristyle** [hubotio/hubot#396]
We're growing a rather long list of commands.  We're using nearly 60 scripts from `hubot-scripts`, the ones from the `hubot` package... and 4 or 5 home grown.

It would be nice to see the `help` command read additional category information from the script comments, for:
- category organized views of commands -- think `help by category`
- the ability to filter commands by category -- think `help for category it`

To make this universally useful, the categories should be standardized -- otherwise, it defeats the purpose.  Examples
- `fun` - animal, meme_generator, news, lmgtfy, invalid, shipit, swanson, fml, facepalm, rotten, eight-ball, filmwise
- `info` - directions, wolfram, google, shorten, snow
- `it` - github-*, graphite, isup, janky, jenkins, jira, sendgrid, travis, uptime-robot

**Comment by arigoldx** [comment]
Any progress here? Given that there is still [just a simple sort](https://github.com/hubotio/hubot/blob/master/src/robot.js#L515) on the list of commands, I'm guessing that not much has changed in the past 6ish years...

Ain't complaining --- just wanted to check in before I roll our own :)

How y'all showing help for your hubot?
