### ISSUE TITLE
Update a local installation of hubot

### ISSUE THREAD

**Issue by philippbeckmann** [hubotio/hubot#420]
Is there an automated way to update hubot when installed via "npm install hubot"? "npm update" can install the new version, but removes the old one completely with its package.json.

**Comment by tonymet** [comment]
@philippbeckmann I use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) to update all of my npm packages easily. This works for your hubot installation and in general for any npm-managed project.  just install that and run `npm-check-updates -u` and `npm install` which will update your package.json and install the updated packages, including hubot
