### ISSUE TITLE
Possible to script Hubot to leave a room?

### ISSUE THREAD

**Issue by erunion** [hubotio/hubot#567]
This is less of an issue, and more of a question.

Is it possible to script Hubot to leave a room on a certain trigger word? I haven't been able to find anything in the robot API, so I'm not sure if I'm looking in the wrong place, or if that just isn't possible (yet).

**Comment by atomicframeworks** [comment]
Rooms could be persisted in Redis.  I tried making the bot say "/part" which normally removes someone from a HipChat room, but in this case the bot was able to say it without leave the room.  Maybe there is there a way to access the raw adapter and manually call it's leave function?
