### ISSUE TITLE
Unix Deployment does not include `init.d` Script Example

### ISSUE THREAD

**Issue by timfallmk** [hubotio/hubot#598]
I noticed in the moved to in-repo documentation, the Unix deployment guide was given a much "higher level" treatment. While "keep-alive" methods are mentioned, there is no  quick-start or example script like the `init.d` one given in the old wiki. Was this intentional?

**Comment by technicalpickles** [comment]
We started a pattern of including example init scripts in the `examples` script, along with some information in docs/deploying/unix.md, in case anyone is interested in helping write those up.
