### ISSUE TITLE
Telegram Adapter for Hubot request

### ISSUE THREAD

**Issue by Winor** [hubotio/hubot#643]
Telegram (https://telegram.org/) is a completely free and secure messaging service with open API and protocol. I think it would be great to see Hubot on Telegram.

**Comment by zenitraM** [comment]
Hey, I created one! It is a bit hacky for now (as it hooks into another scriptable CLI client, [tg](https://github.com/vysheng/tg), to send and receive messages) but it works fine for now.

Find it at: http://github.com/zenitraM/hubot-tg

**Comment by betzerra** [comment]
Congrats @zenitraM! I'll check on it as soon as I can :-)

**Comment by Winor** [comment]
Telegram added HTTPS-based API for bots https://core.telegram.org/bots

**Comment by sergey-litvinov** [comment]
Awesome, that new API supports two way for getting new messages:
1. getUpdates call with long pooling
2. webhook

Also it has much easier way to create new account. 
Finally we will have normal Telegram adapter with small resource requirments! :)

**Comment by kostrse** [comment]
:+1:
