### ISSUE TITLE
Debugging Hubot

### ISSUE THREAD

**Issue by ppatarinski** [hubotio/hubot#648]
Hi everyone, 

I am new to node.js and coffee script. I have hubot running on my windows machine, but what I am trying to accomplish is debug hubot and any of the hubot scripts. How can I got about achieving that? So far I have gotten IntelliJ running and transpiling the coffee script to js. And my breakpoints hit in the index.js (or index.coffee), however stepping over the return new Robot line (line 25 in index.coffee) closes down the application. 

Thank you 
Paul

**Comment by michaelansel** [comment]
@geoffreyanderson I know you have been doing some pretty heavy hubot script development in IntelliJ; could you throw something in [docs/scripting.md](https://github.com/github/hubot/blob/master/docs/scripting.md) with details?

**Comment by victorhooi** [comment]
The book [Automation and Monitoring with Hubot](https://leanpub.com/automation-and-monitoring-with-hubot/read#leanpub-auto-debugging-your-scripts) has a section on debugging.

I've just tested that myself, and it seems to work well. Basically, the steps are:

```
npm install -g node-inspector
node-inspector --no-preload --web-port 8123
```

Then, we can insert `debugger` in our code somewhere to setup a breakpoint.  Then we run Hubot:

```
npm install -g coffeescript
coffee --nodejs --debug node_modules/.bin/hubot
```

Then, we visit `http://127.0.0.1:8123/debug?port=5858 ` in our browser.

I think we should get this into the Hubot documentation. Also, somebody more experienced might have something to add.

**Comment by victorhooi** [comment]
I should also mention, I'm still not sure how to get access to things like `robot` or `msg` from within the node-inspector console though.

**Comment by geoffreyanderson** [comment]
Since yeoman is used to generate a hubot and more hubot scripts are being converted to individual npm packages, there's less need to open the generated hubot repo in IntelliJ.  What we've done is setup basic testing for new scripts in a separate repo and run most of that via the CLI since there seems to be a transpiling dependency for IntellIiJ to follow along.

I'll dig a little more and see if I can figure out a basic enough testing pattern with IntelliJ that plays nicely with this stuff.  I think setting up the transpiler to throw the maps and JS files into a different directory (as per https://www.jetbrains.com/idea/help/transpiling-coffeescript-to-javascript.html#d305745e612) might help get around some issues with scripts getting double-loaded too.

**Comment by geoffreyanderson** [comment]
When you get intellij cleanly setup with a hubot checkout, but #845 makes any runners fail.  If you use #877 it appears to fix the problem with starting a runner from IntelliJ.

As for debugging from IntelliJ...it seems like the various permutations of a nodejs runner either can't be used in a debug mode or can only load a javascript console such that you can't access STDIN to invoke specific script commands (boo :( )

If folks still want to setup a new intellij project, the high-level set of steps are:
* Generate your bot following [Getting Started With Hubot](https://hubot.github.com/docs/)
* In IntelliJ, create a new empty project
* set "Project Location" to your generated bot repository
* Add your generated bot repository as a module for your project
    * In the "Project Structure" dialog, go to "Modules", click the "+" button then choose "Import modules"
    ![screen shot 2015-03-13 at 13 58 46](https://cloud.githubusercontent.com/assets/423529/6647216/41215d20-c989-11e4-9a48-2205b140cd71.png)
    * Choose "Create module form existing sources" and hit "Next"
    * Make sure the path to your generated bot repository is checked and hit "Finish"
    * You should now see your generated bot repository as a module in the project structure dialog.
* [Setup a file watcher](https://www.jetbrains.com/idea/help/transpiling-coffeescript-to-javascript.html) to transpile coffeescript. To avoid issues with the transpiled JS files colliding with your .coffee files, set them up to use a `js` directory.
    * Set the "Arguments" field to `--output $ProjectFileDir$/js/ --map --compile $FileName$`
    * Set the "Output paths to refresh" field to `$ProjectFileDir$/js/$FileNameWithoutExtension$.js:$ProjectFileDir$/js/$FileNameWithoutExtension$.map`
* Create a "Node.js" run configuration
    * Set the "Node interpreter" field to your coffeescript executable (e.g. `/usr/local/bin/coffee`)
    * Set the "Working directory" field to your generated bot repository path
    * set the "Javascript file" field to `node_modules/.bin/hubot`
    * ![screen shot 2015-03-13 at 14 16 25](https://cloud.githubusercontent.com/assets/423529/6647452/95a85e00-c98b-11e4-89af-c296d03ff0ad.png)

**Comment by mecampbellsoup** [comment]
Does anyone know of a solid pattern for testing/debugging individual scripts (e.g. `something.coffee`) that one is writing to extend Hubot's capabilities? One of ours has broken and I'm struggling to do basic things like inspect objects, log output, etc.

**Comment by technicalpickles** [comment]
For inspect based debugging in development, I usually include a line like:

```coffeescript
console.log require('util').inspect thingToDebug
```

When using the shell adapter in development, that should be logged to the console.

If you are debugging something in production, you'll want to log with `robot.logger` instead, ie `robot.logger.debug`, `robot.logger.error`, `robot.logger.info`, etc. The default log level is `info` but you can change with the HUBOT_LOG_LEVEL environment variable.

**Comment by GGYaX** [comment]
Hi Paul, try this out : a doc about setting up coffee in Intellij https://www.jetbrains.com/help/idea/2017.1/debugging-coffeescript.html. I remember the debug point can be set in coffee file directly.

**Comment by timkinnane** [comment]
x-post from Slack discussion on same topic...

I've had some success using atom and xatom-debug with unit tests, by running mocha with the `--inspector` flag, then setting xatom-debug to 'remote' mode, which watches the inspector port to debug remote processes. That will allow watching and reloading through the debugger or through a `--watch` flag on mocha and if you also run mocha with `--inspector-brk`, it won't execute tests until the debugger attaches, which is pretty neat. You still run into the problem of debugging compiled coffeescript. Trying to relate stack traces back to what's happening in your hubot coffee scripts is a major pain. No magic bullet yet, but I'm working on it.

**Comment by timkinnane** [comment]
Pinging this thread to keep stale bot's hands off it. I wouldn't consider it closed until there's a standard recommended and documented approach to running hubot with node debug enabled. Which I can hopefully provide myself, just haven't got to it yet.
