### ISSUE TITLE
Use a respond as a fallback

### ISSUE THREAD

**Issue by sobrinho** [hubotio/hubot#683]
Hey guys,

We have a service that we can chat with the bot (AI) and we don't want hubot calling it when other plugins already did something.

That's the plugin:

``` coffee
module.exports = (robot) ->
  robot.respond /(.+)/i, (msg) ->
    msg
      .http("http://www.ed.conpet.gov.br/mod_perl/bot_gateway.cgi")
      .query(server: "0.0.0.0:8085", charset_post: "utf-8", pure: 1, msg: msg.match[1])
      .get() (err, res, body) ->
        msg.reply body.replace(/<[^<>]*>/g, "")
```

If I have another plugin like this one:

``` coffee
module.exports = (robot) ->
        uis = [
                "http://2.bp.blogspot.com/--Tt_oRekUSE/T62ZFQF_kdI/AAAAAAAAOvk/0BmpdLRxe0U/s1600/meme+UI+colorido.png",
                "http://youpix.com.br/wp-content/uploads/2012/01/ui.jpg"]
        robot.hear /\bui\b/i, (msg) ->
                msg.send msg.random uis
```

And send a message like `hubot ui` it will call both.

That's possible? I mean, a fallback respond that got called only when no other respond matched?

**Comment by michaelansel** [comment]
I've got a commit ready to add code, docs, and tests for `catchAllAddressed`. I'll create a PR once #841 merges (needed for the testing foundation). For now, michaelansel/hubot@a512cfc231be55a98e8b89d89ef9d20f5fd43021

**Comment by technicalpickles** [comment]
@michaelansel https://github.com/github/hubot/pull/841 is merged now 😁 

Maybe this is a good opportunity to try out the [Hubot Evolution](https://github.com/hubotio/evolution/) for new feature proposals?

**Comment by michaelansel** [comment]
#868 is the fix for this issue. Looks like it needs some conflict resolution.
