### ISSUE TITLE
Document redis providers on heroku, and recommend adding plan with persistence

### ISSUE THREAD

**Issue by technicalpickles** [hubotio/hubot#704]
Comparing https://addons.heroku.com/rediscloud and https://addons.heroku.com/redistogo, neither of them backups. Users should be advised to add a pay plan if they are concerned about keeping the data kept in hubot's brain around.

cc https://github.com/github/hubot/pull/689

**Comment by mose** [comment]
Is this still the case? checking https://redislabs.com/products/redis-cloud/compare/ I have a doubt.

**Comment by technicalpickles** [comment]
I looked at https://addons.heroku.com/rediscloud and https://addons.heroku.com/redistogo and both have 'backups' grayed out at their free tier. Paid tiers above it don't gray it out.
