### ISSUE TITLE
Content-Encoding issue

### ISSUE THREAD

**Issue by cha55son** [hubotio/hubot#939]
https://github.com/expressjs/body-parser/issues/100

I've got an app that is submitting webhooks (POST) to hubot. When hubot receives the webhook it throws the error in the issue above. I do not have access to change the app sending the post requests but I can change hubot however I need to. Therefore it would make sense to have a way to insert express middleware before hubot binds it's own middleware (this would have to be done in an init script I would assume), or possibly a way to insert middleware at the beginning of the stack when my script loads. Then I would at least be able to do something like this:

``` coffeescript
robot.router.insertMiddleware (app) ->
  app.use (req, res, next) ->
    delete req.headers['content-encoding']
    next()
})
robot.router.post '/receiving/wrong/headers', (req, res) ->
  ...
```

https://github.com/github/hubot/blob/5ec8f375f3ac97e9df6e45c6b459d42025b74694/src/robot.coffee#L284

To be clear the HTTP header hubot is receiving is invalid. There is no **Content-Encoding: UTF-8** header allowed. [HTTP Content-Encoding](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.11) Therefore it would make sense that express/body-parser throws that warning. If you know of a way around this or an improvement on the design above your opinion would be greatly appreciated.

**Comment by michaelansel** [comment]
I don't know of a way to insert middleware into the Express stack other than at load time. There is an open issue somewhere for pulling Express out of the core, but I don't think anyone has had time to work on it.

I'm not sure of a good solution here other than fixing the bad application or finishing the refactor to hubot-express.

**Comment by WOLVIE97** [comment]
Woowww!!!!?

**Comment by mose** [comment]
I managed to add an express middleware after load time in a plugin. It's a bit hacky but it works:

https://github.com/Gandi/hubot-restrict-ip/blob/master/scripts/restrict_ip.coffee#L81

Anyways, I think/hope hubot3 will give a special attention to express modularity and tunability.

**Comment by technicalpickles** [comment]
@mose this is one of the examples I was talking about over in https://github.com/github/hubot/issues/767
