### ISSUE TITLE
Refine and automate release process

### ISSUE THREAD

**Issue by technicalpickles** [hubotio/hubot#965]
I walked through the process with @bhuga, @bkeepers, and @michaelansel and there is definitely some tedious points.

See  https://github.com/github/hubot/blob/master/CONTRIBUTING.md#releasing for the current process. Particularly tedious things:
- [ ] generating ChangeLog summary from PRs merged
- [ ] generating a PR with links to PRs, cc author, etc
- [ ] push a prerelease package (`hubot@next`) and execute functional tests
- [ ] promote prelease package (`npm dist-tag add hubot@<version> latest`)
- [ ] update hubot.github.com's submodule of github/hubot docs directory

**Comment by jasonkarns** [comment]
marginally related: any particular reason why there is a release script when npm has `npm version` built in?

**Comment by jasonkarns** [comment]
I guess the general question is why there are so many bash scripts in the first place? Most all of them could be replaced (and simplified) with npm scripts. For instance, nearly every bash script has to mess with modifying the PATH so that node_modules bins are available. That is unnecessary when using npm scripts since npm prepends `$(npm bin)` to the path automatically.

This is already a node project, and it would be more conventional to have `npm test`, `npm start` and see all the other available scripts with `npm run`.

I would be happy to put together PR illustrating the change, if it would be considered.

**Comment by technicalpickles** [comment]
> any particular reason why there is a release script when npm has npm version built in?

Yes, the reason is we didn't know about it :grin: 

For what it's worth, we are currently updating package.json separate from actually pushing it. By doing this, we can do a PR which includes the PR, and then publish it after.

**Comment by technicalpickles** [comment]
>  I guess the general question is why there are so many bash scripts in the first place? Most all of them could be replaced (and simplified) with npm scripts. For instance, nearly every bash script has to mess with modifying the PATH so that node_modules bins are available. That is unnecessary when using npm scripts since npm prepends $(npm bin) to the path automatically.

Part of it is conventions used at GitHub for development. Nearly every project has a `script/bootstrap` for initializing the local environment, `script/test` for running test, `script/server` for launching the server process.

Another part is that hubot is old enough that I don't think these conventions were as well established when it was written, and they just haven't been updated.

> This is already a node project, and it would be more conventional to have npm test, npm start and see all the other available scripts with npm run.

I'd be amenable to using these conventions. It would be good to keep some of the scripts around though for consistency with our other projects.

---

Also to be clear, these points don't address any of the pain points I outlined in the original issue, so they aren't as much of a priority for me.

**Comment by jasonkarns** [comment]
> For what it's worth, we are currently updating package.json separate from actually pushing it. By doing this, we can do a PR which includes the PR, and then publish it after.

`npm version` bumps package.json (it accepts `major`, `minor`, `patch`, `premajor`, `preminor`, `prepatch`, `prerelease` or an exact version to set); commits the package.json change, and tags it accordingly. It doesn't do git-pushing or npm-publishing automatically. If you *want* that, I typically do:

``` json
"scripts": {
  "release": "npm version",
  "postrelease": "git push && npm publish"
}
```

but out of the box, npm version only does the bump/commit/tag. (which is what you want, I believe)



> Also to be clear, these points don't address any of the pain points I outlined in the original issue, so they aren't as much of a priority for me.

Agreed. I'll open a separate issue/PR for discussion so I don't hijack this thread any further :)

**Comment by technicalpickles** [comment]
I tried https://github.com/skywinder/github-changelog-generator for https://github.com/github/hubot/pull/1035 with mixed results.

It kind of wants to take over the changelog, which I wasn't ready to do yet. I tried specifying `--since-tag v2.15.0`, expecting it would only output stuff for the next release, but it basically attributed everything to the next release. It also wants to work with releases that are actually published, so it assumes any changes since are 'unreleased', which doesn't work as well for our PR based release flow.

**Comment by michaelansel** [comment]
To get the change list, a partially working solution:
```
git log latest..HEAD | grep "^Merge"
```

It isn't great though because it will pick up nested merges. I'm sure there is a way with better git-fu to actually generate the correct list of merge commits against master containing a PR reference.

An addition to the Release PR: Add a compare link between the latest release tag and HEAD and then a link between the latest release tag and the new release tag. e.g. https://github.com/github/hubot/compare/v2.15.0...v2.16.0  `https://github.com/github/hubot/compare/v2.15.0...v2.16.0`

**Comment by jasonkarns** [comment]
Per my work on #978, I would love to see the new release process leverage as much OOTB npm functionality as possible. To that end, I'd like to make everyone aware that recent versions of npm have some new functionality. Previously, npm had the `npm version` command that auto-bumps the version, commits and tags. What's new (as of 2.2 IIRC), there are `preversion` and `postversion` lifecycle hooks. Typically `preversion` is used to run tests, `version` runs the build and adds the build assets to git index, and `postversion` would git-push and npm-publish. There are no defaults for `preversion` and `postversion`, however, so they could do whatever you like. The `preversion

**Comment by jasonkarns** [comment]
I could roughly see the scripts broken down roughly:

- `preversion`: run tests
- `version`: build/compile and smoketest if applicable; generate changelog (version has already been bumped at this point, so it can be read from package.json and incorporated into the changelog); git-add changelog and any other build assets to git index
- `postversion`: push to github, publish to npm, update hubot.github.com's submodule of github/hubot docs directory

Obviously, you folks know your desired release process better than I, but the npm's new version lifecycle hooks can be used to eliminate the npm-specific steps from your custom scripts.

**Comment by technicalpickles** [comment]
The current way I'm generating the changelog is with github-changelog-generator. The invocation is `CHANGELOG_GITHUB_TOKEN=secret github_changelog_generator --future-release vX.Y.Z`

**Comment by technicalpickles** [comment]
We've talked about using [semantic-release](https://github.com/semantic-release/semantic-release) for this.

**Comment by xurizaemon** [comment]
Closing this proactively, as of v4.0.0 we have automated releases.

There are some other tasks in this issue's checklist from 2015 which IMO best moved to separate issues if they are still something to pursue.
